// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CmdConstants.proto

package proto;

public final class CmdConstantsProto {
  private CmdConstantsProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code proto.CmdCode}
   */
  public enum CmdCode
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>SERVER_ERROR = 5000;</code>
     *
     * <pre>
     *错误命令
     * </pre>
     */
    SERVER_ERROR(0, 5000),
    /**
     * <code>LOGINSERVER_LOGIN_BYPHONE = 99;</code>
     *
     * <pre>
     *手机登陆登陆
     * </pre>
     */
    LOGINSERVER_LOGIN_BYPHONE(1, 99),
    /**
     * <code>LOGINSERVER_LOGIN = 100;</code>
     *
     * <pre>
     *登陆服务器命令
     * </pre>
     */
    LOGINSERVER_LOGIN(2, 100),
    /**
     * <code>LOGINSERVER_REGIST = 101;</code>
     *
     * <pre>
     *注册
     * </pre>
     */
    LOGINSERVER_REGIST(3, 101),
    /**
     * <code>GAMEROOM_LIST = 300;</code>
     *
     * <pre>
     * 获取房间列表命令
     * </pre>
     */
    GAMEROOM_LIST(4, 300),
    /**
     * <code>GAMETYPE_LIST = 301;</code>
     *
     * <pre>
     * 游戏类型命令
     * </pre>
     */
    GAMETYPE_LIST(5, 301),
    /**
     * <code>GAMEINFOOFGAMETYPE = 302;</code>
     *
     * <pre>
     *游戏信息
     * </pre>
     */
    GAMEINFOOFGAMETYPE(6, 302),
    /**
     * <code>GAMEROOMTYPE_LIST = 303;</code>
     *
     * <pre>
     *游戏房间类型
     * </pre>
     */
    GAMEROOMTYPE_LIST(7, 303),
    /**
     * <code>GAMEROOMTYPE = 304;</code>
     *
     * <pre>
     *游戏房间分类
     * </pre>
     */
    GAMEROOMTYPE(8, 304),
    /**
     * <code>USERLOCKMACHINE = 305;</code>
     *
     * <pre>
     *用户锁定本机
     * </pre>
     */
    USERLOCKMACHINE(9, 305),
    /**
     * <code>LOGINSERVER_SYSMESG = 306;</code>
     *
     * <pre>
     * 系统弹出框消息
     * </pre>
     */
    LOGINSERVER_SYSMESG(10, 306),
    /**
     * <code>LOGINSERVER_PUBLIC_SYSMESG = 307;</code>
     *
     * <pre>
     *通用系统消息
     * </pre>
     */
    LOGINSERVER_PUBLIC_SYSMESG(11, 307),
    /**
     * <code>BANK_RECORD_QUERY = 400;</code>
     *
     * <pre>
     *公共命令
     * </pre>
     */
    BANK_RECORD_QUERY(12, 400),
    /**
     * <code>BANK_QUERY = 401;</code>
     *
     * <pre>
     * 银行信息查询命令
     * </pre>
     */
    BANK_QUERY(13, 401),
    /**
     * <code>BANK_SAVE = 402;</code>
     *
     * <pre>
     *存游戏币
     * </pre>
     */
    BANK_SAVE(14, 402),
    /**
     * <code>BANK_TAKE = 403;</code>
     *
     * <pre>
     *提取游戏币
     * </pre>
     */
    BANK_TAKE(15, 403),
    /**
     * <code>BANK_TRANSFER = 404;</code>
     *
     * <pre>
     *游戏币转账
     * </pre>
     */
    BANK_TRANSFER(16, 404),
    /**
     * <code>BANK_EXCHANGE = 405;</code>
     *
     * <pre>
     *充值金币兑换游戏币
     * </pre>
     */
    BANK_EXCHANGE(17, 405),
    /**
     * <code>BANK_PROP_TO_SCORE = 406;</code>
     *
     * <pre>
     *奖券转换为幸运豆
     * </pre>
     */
    BANK_PROP_TO_SCORE(18, 406),
    /**
     * <code>TAKE_GOLD = 407;</code>
     *
     * <pre>
     *救济金自动领取
     * </pre>
     */
    TAKE_GOLD(19, 407),
    /**
     * <code>TIME_SYN = 408;</code>
     *
     * <pre>
     * 同步时间
     * </pre>
     */
    TIME_SYN(20, 408),
    /**
     * <code>GET_GOODS_VALUE = 409;</code>
     *
     * <pre>
     * 获取商品价值
     * </pre>
     */
    GET_GOODS_VALUE(21, 409),
    /**
     * <code>GIVE_ROSE = 410;</code>
     *
     * <pre>
     * 赠送道具
     * </pre>
     */
    GIVE_ROSE(22, 410),
    /**
     * <code>GIVE_ROSE_OTHER = 411;</code>
     *
     * <pre>
     * 赠送人获取奖品
     * </pre>
     */
    GIVE_ROSE_OTHER(23, 411),
    /**
     * <code>GAMEPAYOK = 412;</code>
     *
     * <pre>
     * 游戏支付成功
     * </pre>
     */
    GAMEPAYOK(24, 412),
    /**
     * <code>USERCONTROL = 413;</code>
     *
     * <pre>
     * 用户AB 控制
     * </pre>
     */
    USERCONTROL(25, 413),
    /**
     * <code>USERINVITEDSCORECMD = 414;</code>
     *
     * <pre>
     *用户被邀请(用户使用邀请码兑换奖励)
     * </pre>
     */
    USERINVITEDSCORECMD(26, 414),
    /**
     * <code>INVITEUSERSCORECMD = 415;</code>
     *
     * <pre>
     *邀请用户(用户邀请到一定数量玩家时领取对应档次的奖励)
     * </pre>
     */
    INVITEUSERSCORECMD(27, 415),
    /**
     * <code>USER_SEND_RADPACKET = 416;</code>
     *
     * <pre>
     *用户封红包
     * </pre>
     */
    USER_SEND_RADPACKET(28, 416),
    /**
     * <code>USER_GET_RADPACKET = 417;</code>
     *
     * <pre>
     *用户获得红包
     * </pre>
     */
    USER_GET_RADPACKET(29, 417),
    /**
     * <code>INVITEUSERCOUNTCMD = 418;</code>
     *
     * <pre>
     *已经邀请过的用户数量(用户查询邀请多的用户)
     * </pre>
     */
    INVITEUSERCOUNTCMD(30, 418),
    /**
     * <code>INVITEORSHARECOUNT = 419;</code>
     *
     * <pre>
     *用户查询分享，邀请到的玩家数量
     * </pre>
     */
    INVITEORSHARECOUNT(31, 419),
    /**
     * <code>INVITEORSHARE = 420;</code>
     *
     * <pre>
     *用户分享，邀请领取奖励
     * </pre>
     */
    INVITEORSHARE(32, 420),
    /**
     * <code>TRANS_STR_IN = 421;</code>
     *
     * <pre>
     *传递字符串给登录服务器
     * </pre>
     */
    TRANS_STR_IN(33, 421),
    /**
     * <code>SHARE_QUERY = 422;</code>
     *
     * <pre>
     *分享赚取积分,已经分享积分开宝箱子,add by 2016.05.14
     * </pre>
     */
    SHARE_QUERY(34, 422),
    /**
     * <code>SHARE_SUCCESS_NOTICE = 423;</code>
     *
     * <pre>
     *用户分享成功后通知服务器邀请领取奖励,ShareSuccessReq-&gt;ShareSuccessResp
     * </pre>
     */
    SHARE_SUCCESS_NOTICE(35, 423),
    /**
     * <code>SHARE_OPEN_BOX = 424;</code>
     *
     * <pre>
     *开积分宝箱,ShareOpenBoxReq-&gt;ShareOpenBoxResp
     * </pre>
     */
    SHARE_OPEN_BOX(36, 424),
    /**
     * <code>SHARE_QUERY_DETAIL = 425;</code>
     *
     * <pre>
     *查询积分贡献榜,empty-&gt;ShareScoreDetailResp
     * </pre>
     */
    SHARE_QUERY_DETAIL(37, 425),
    /**
     * <code>PRESENT_QUERY = 430;</code>
     *
     * <pre>
     *银行赠送,add by 2016.05.25
     * </pre>
     */
    PRESENT_QUERY(38, 430),
    /**
     * <code>PRESENT_GOLD = 431;</code>
     *
     * <pre>
     *赠送金币，PresentGoldReq-&gt;PresentQueryResp
     * </pre>
     */
    PRESENT_GOLD(39, 431),
    /**
     * <code>BULLSCORE_USE_LIST = 433;</code>
     *
     * <pre>
     *add by 2016.06.04
     * </pre>
     */
    BULLSCORE_USE_LIST(40, 433),
    /**
     * <code>BULLSCORE_USE = 434;</code>
     *
     * <pre>
     *券兑换,BullScoreUseReq,BullScoreUseResp
     * </pre>
     */
    BULLSCORE_USE(41, 434),
    /**
     * <code>BULLSCORE_USE_HISTORY = 435;</code>
     *
     * <pre>
     *牛券兑换明细,BullScoreUseHistoryReq,BullScoreUseHistoryResp
     * </pre>
     */
    BULLSCORE_USE_HISTORY(42, 435),
    /**
     * <code>PAY_IOS_RECEIPRT = 440;</code>
     *
     * <pre>
     *add by 2016.08.06
     * </pre>
     */
    PAY_IOS_RECEIPRT(43, 440),
    /**
     * <code>PAY_INDEX = 441;</code>
     *
     * <pre>
     *add by 2016.08.23
     * </pre>
     */
    PAY_INDEX(44, 441),
    /**
     * <code>USERINFO_GETCOMMONINFO = 800;</code>
     *
     * <pre>
     *用户中心命令
     * </pre>
     */
    USERINFO_GETCOMMONINFO(45, 800),
    /**
     * <code>USERINFO_GETDETAILINFO = 801;</code>
     *
     * <pre>
     *获取用户的详细信息
     * </pre>
     */
    USERINFO_GETDETAILINFO(46, 801),
    /**
     * <code>USERINFO_UPDATE_LOGINPWD = 802;</code>
     *
     * <pre>
     *修改用户的登录密码
     * </pre>
     */
    USERINFO_UPDATE_LOGINPWD(47, 802),
    /**
     * <code>USERINFO_UPDATE_INSUREPWD = 803;</code>
     *
     * <pre>
     *修改用户的保险柜密码
     * </pre>
     */
    USERINFO_UPDATE_INSUREPWD(48, 803),
    /**
     * <code>USERINFO_UPDATE_COMMONINFO = 804;</code>
     *
     * <pre>
     *修改用户的普通信息
     * </pre>
     */
    USERINFO_UPDATE_COMMONINFO(49, 804),
    /**
     * <code>USERINFO_UPDATE_DETAILINFO = 805;</code>
     *
     * <pre>
     *修改用户的详细信息
     * </pre>
     */
    USERINFO_UPDATE_DETAILINFO(50, 805),
    /**
     * <code>USERINFO_QMFD_JOINGAME = 806;</code>
     *
     * <pre>
     *参加"全民福袋"活动
     * </pre>
     */
    USERINFO_QMFD_JOINGAME(51, 806),
    /**
     * <code>USERINFO_QMFD_RANKING = 807;</code>
     *
     * <pre>
     *"全民福袋"活动单局排名
     * </pre>
     */
    USERINFO_QMFD_RANKING(52, 807),
    /**
     * <code>USERINFO_QMFD_SETTLEMENT = 808;</code>
     *
     * <pre>
     *"全民福袋"活动单局结算
     * </pre>
     */
    USERINFO_QMFD_SETTLEMENT(53, 808),
    /**
     * <code>USERINFO_QMFD_STARTUP = 809;</code>
     *
     * <pre>
     *向客户端推动"全民福袋"开始信息
     * </pre>
     */
    USERINFO_QMFD_STARTUP(54, 809),
    /**
     * <code>USERINFO_ZZ_GET = 810;</code>
     *
     * <pre>
     * 得到粽子活动的信息
     * </pre>
     */
    USERINFO_ZZ_GET(55, 810),
    /**
     * <code>USERINFO_ZZ_RANK = 811;</code>
     *
     * <pre>
     * 得到活动的排名信息
     * </pre>
     */
    USERINFO_ZZ_RANK(56, 811),
    /**
     * <code>USERINFO_ZZ_OPEN = 812;</code>
     *
     * <pre>
     * 剥粽子的排名信息
     * </pre>
     */
    USERINFO_ZZ_OPEN(57, 812),
    /**
     * <code>USERINFO_ZZ_BUY = 813;</code>
     *
     * <pre>
     * 买粽子
     * </pre>
     */
    USERINFO_ZZ_BUY(58, 813),
    /**
     * <code>USERINFO_RANK_SHOW = 814;</code>
     *
     * <pre>
     *查看排行榜
     * </pre>
     */
    USERINFO_RANK_SHOW(59, 814),
    /**
     * <code>USERINFO_RANK_THUMB_UP = 815;</code>
     *
     * <pre>
     *排行榜点赞
     * </pre>
     */
    USERINFO_RANK_THUMB_UP(60, 815),
    /**
     * <code>USERINFO_RANK_RECV_AWARD = 816;</code>
     *
     * <pre>
     *排行榜领取奖励
     * </pre>
     */
    USERINFO_RANK_RECV_AWARD(61, 816),
    /**
     * <code>LOGINSERVER_QIANDAO_INDEX = 819;</code>
     *
     * <pre>
     *签到加载信息
     * </pre>
     */
    LOGINSERVER_QIANDAO_INDEX(62, 819),
    /**
     * <code>LOGINSERVER_QIANDAO = 820;</code>
     *
     * <pre>
     *签到
     * </pre>
     */
    LOGINSERVER_QIANDAO(63, 820),
    /**
     * <code>LOGINSERVER_QIANDAO_RECV_TOTAL = 821;</code>
     *
     * <pre>
     *领取累计签到x天的奖励
     * </pre>
     */
    LOGINSERVER_QIANDAO_RECV_TOTAL(64, 821),
    /**
     * <code>LOGINSERVER_QIANDAO_CHANGE_TIME = 822;</code>
     *
     * <pre>
     *累计签到设置当前第几天
     * </pre>
     */
    LOGINSERVER_QIANDAO_CHANGE_TIME(65, 822),
    /**
     * <code>LOGINSERVER_MATCH_FETCH_ACT_LIST = 8301;</code>
     *
     * <pre>
     *拉取赛事活动列表
     * </pre>
     */
    LOGINSERVER_MATCH_FETCH_ACT_LIST(66, 8301),
    /**
     * <code>LOGINSERVER_MATCH_BAO_MING = 8302;</code>
     *
     * <pre>
     *报名参加比赛
     * </pre>
     */
    LOGINSERVER_MATCH_BAO_MING(67, 8302),
    /**
     * <code>LOGINSERVER_MATCH_CANCEL = 8303;</code>
     *
     * <pre>
     *取消参加比赛
     * </pre>
     */
    LOGINSERVER_MATCH_CANCEL(68, 8303),
    /**
     * <code>LOGINSERVER_MATCH_FETCH_TYPES = 8304;</code>
     *
     * <pre>
     *获取特定比赛类型的赛事列表
     * </pre>
     */
    LOGINSERVER_MATCH_FETCH_TYPES(69, 8304),
    /**
     * <code>LOGINSERVER_MATCH_FETCH_TYPE_DETAIL = 8305;</code>
     *
     * <pre>
     *点击五元话费场,打开详情框
     * </pre>
     */
    LOGINSERVER_MATCH_FETCH_TYPE_DETAIL(70, 8305),
    /**
     * <code>LOGINSERVER_MATCH_REFRESH_PERSON_COUNT = 8306;</code>
     *
     * <pre>
     *客户端定时刷新当前比赛报名人数
     * </pre>
     */
    LOGINSERVER_MATCH_REFRESH_PERSON_COUNT(71, 8306),
    /**
     * <code>LOGINSERVER_MATCH_BEGIN = 8307;</code>
     *
     * <pre>
     *服务器通知全部报了名的客户端比赛开始
     * </pre>
     */
    LOGINSERVER_MATCH_BEGIN(72, 8307),
    /**
     * <code>LOGINSERVER_MATCH_GIVEUP = 8308;</code>
     *
     * <pre>
     *比赛开始的命令推送给玩家后,玩家选择放弃按钮,不来参加比赛
     * </pre>
     */
    LOGINSERVER_MATCH_GIVEUP(73, 8308),
    /**
     * <code>LOGINSERVER_MATCH_BEGIN_PULL = 8309;</code>
     *
     * <pre>
     *玩家登陆时,推送已经开始的比赛
     * </pre>
     */
    LOGINSERVER_MATCH_BEGIN_PULL(74, 8309),
    /**
     * <code>LOGIN_SERVER_CHAT_SEND = 8310;</code>
     *
     * <pre>
     *LOGIN聊天发送信息
     * </pre>
     */
    LOGIN_SERVER_CHAT_SEND(75, 8310),
    /**
     * <code>LOGIN_SERVER_CHAT_RECEIVE = 8311;</code>
     *
     * <pre>
     *LOGIN聊天发送信息
     * </pre>
     */
    LOGIN_SERVER_CHAT_RECEIVE(76, 8311),
    /**
     * <code>GAME_SERVER_CHAT_SEND = 8312;</code>
     *
     * <pre>
     *game聊天发送信息
     * </pre>
     */
    GAME_SERVER_CHAT_SEND(77, 8312),
    /**
     * <code>GAME_SERVER_CHAT_RECEIVE = 8313;</code>
     *
     * <pre>
     *game聊天发送信息
     * </pre>
     */
    GAME_SERVER_CHAT_RECEIVE(78, 8313),
    /**
     * <code>GAME_SERVER_REFRESH_USER_STATUS = 8314;</code>
     *
     * <pre>
     *后台禁言玩家后,hub通知游戏服务器更新状态
     * </pre>
     */
    GAME_SERVER_REFRESH_USER_STATUS(79, 8314),
    /**
     * <code>GAME_SERVER_UPDATE_NOTICE_LIST = 8315;</code>
     *
     * <pre>
     *后台修改系统公告后,通知game server
     * </pre>
     */
    GAME_SERVER_UPDATE_NOTICE_LIST(80, 8315),
    /**
     * <code>LOGIN_SERVER_CHAT_DLG_OPERATION = 8316;</code>
     *
     * <pre>
     *用户打开或者关闭聊天窗口
     * </pre>
     */
    LOGIN_SERVER_CHAT_DLG_OPERATION(81, 8316),
    /**
     * <code>SERVER_REFRESH_SERVER_STATUS = 8317;</code>
     *
     * <pre>
     *hub通知游戏服务器更新状态
     * </pre>
     */
    SERVER_REFRESH_SERVER_STATUS(82, 8317),
    /**
     * <code>LOGIN_SERVER_SUPER_CHARGE = 8318;</code>
     */
    LOGIN_SERVER_SUPER_CHARGE(83, 8318),
    /**
     * <code>LOGIN_SERVER_MATCH_OL_COUNT = 8319;</code>
     */
    LOGIN_SERVER_MATCH_OL_COUNT(84, 8319),
    /**
     * <code>LOGIN_GET_SCORE = 8320;</code>
     *
     * <pre>
     *登录领取幸运豆推送消息
     * </pre>
     */
    LOGIN_GET_SCORE(85, 8320),
    /**
     * <code>GET_FREE_SCORE = 8321;</code>
     *
     * <pre>
     *从推送中领取幸运豆
     * </pre>
     */
    GET_FREE_SCORE(86, 8321),
    /**
     * <code>GAMESERVER_LOGIN = 200;</code>
     *
     * <pre>
     *游戏服务器命令
     * </pre>
     */
    GAMESERVER_LOGIN(87, 200),
    /**
     * <code>GAMESERVER_OTHERLOGIN = 201;</code>
     *
     * <pre>
     *其他玩家登陆成功
     * </pre>
     */
    GAMESERVER_OTHERLOGIN(88, 201),
    /**
     * <code>GAMESERVER_LOGIN_BYID = 202;</code>
     *
     * <pre>
     * ID 登陆服务器
     * </pre>
     */
    GAMESERVER_LOGIN_BYID(89, 202),
    /**
     * <code>GAMESERVER_LOGIN_BYPHONE = 203;</code>
     *
     * <pre>
     * 手机 登陆
     * </pre>
     */
    GAMESERVER_LOGIN_BYPHONE(90, 203),
    /**
     * <code>GAMESERVER_SYS_TIME = 204;</code>
     *
     * <pre>
     * 时间同步
     * </pre>
     */
    GAMESERVER_SYS_TIME(91, 204),
    /**
     * <code>SERVER_HEART = 3000;</code>
     *
     * <pre>
     * 心跳检测
     * </pre>
     */
    SERVER_HEART(92, 3000),
    /**
     * <code>SERVER_REG = 2000;</code>
     *
     * <pre>
     * 注册协调服务器命令
     * </pre>
     */
    SERVER_REG(93, 2000),
    /**
     * <code>GAME_ROOMINFO = 500;</code>
     *
     * <pre>
     * 游戏 房间信息
     * </pre>
     */
    GAME_ROOMINFO(94, 500),
    /**
     * <code>GAME_USERINFO = 501;</code>
     *
     * <pre>
     * 用户信息
     * </pre>
     */
    GAME_USERINFO(95, 501),
    /**
     * <code>GAME_TABLEINFO = 502;</code>
     *
     * <pre>
     * 桌子状态信息
     * </pre>
     */
    GAME_TABLEINFO(96, 502),
    /**
     * <code>GAME_MATCHINFO = 503;</code>
     *
     * <pre>
     * 最新赛事
     * </pre>
     */
    GAME_MATCHINFO(97, 503),
    /**
     * <code>GAMESERVER_MACHINFO = 7000;</code>
     *
     * <pre>
     * 请求比赛信息
     * </pre>
     */
    GAMESERVER_MACHINFO(98, 7000),
    /**
     * <code>GAMESERVER_MACHSIGUP = 7001;</code>
     *
     * <pre>
     * 比赛报名
     * </pre>
     */
    GAMESERVER_MACHSIGUP(99, 7001),
    /**
     * <code>GAMESERVER_WITHDRAW = 7002;</code>
     *
     * <pre>
     * 退出比赛
     * </pre>
     */
    GAMESERVER_WITHDRAW(100, 7002),
    /**
     * <code>GAMESERVER_ENTERROOM = 8000;</code>
     *
     * <pre>
     * 用户进入房间
     * </pre>
     */
    GAMESERVER_ENTERROOM(101, 8000),
    /**
     * <code>GAMESERVER_ENTERROOMTABLESTATE = 8001;</code>
     *
     * <pre>
     * 向玩家推送的桌子状态
     * </pre>
     */
    GAMESERVER_ENTERROOMTABLESTATE(102, 8001),
    /**
     * <code>GAMESERVER_OTHERENTERROOM = 8002;</code>
     *
     * <pre>
     * 其他玩家进入房间
     * </pre>
     */
    GAMESERVER_OTHERENTERROOM(103, 8002),
    /**
     * <code>GAMESERVER_CHAIRREQ = 8003;</code>
     *
     * <pre>
     * 请求椅子用户信息
     * </pre>
     */
    GAMESERVER_CHAIRREQ(104, 8003),
    /**
     * <code>GAMESERVER_STANDUP = 8004;</code>
     *
     * <pre>
     * 用户站起
     * </pre>
     */
    GAMESERVER_STANDUP(105, 8004),
    /**
     * <code>GAMESERVER_OTHERSTANDUP = 8005;</code>
     *
     * <pre>
     * 当前桌子玩家得到 得到退出用户信息
     * </pre>
     */
    GAMESERVER_OTHERSTANDUP(106, 8005),
    /**
     * <code>GAMESERVER_LIVEROMM = 8007;</code>
     *
     * <pre>
     *用户离开房间
     * </pre>
     */
    GAMESERVER_LIVEROMM(107, 8007),
    /**
     * <code>GAMESERVER_ENTERROOM_BYMOBILE = 8008;</code>
     *
     * <pre>
     *手机用户坐下操作
     * </pre>
     */
    GAMESERVER_ENTERROOM_BYMOBILE(108, 8008),
    /**
     * <code>GAMESERVER_BANK_QUERY = 8009;</code>
     *
     * <pre>
     * 银行信息查询命令
     * </pre>
     */
    GAMESERVER_BANK_QUERY(109, 8009),
    /**
     * <code>GAMESERVER_BANK_TAKE = 8010;</code>
     *
     * <pre>
     *提取游戏币
     * </pre>
     */
    GAMESERVER_BANK_TAKE(110, 8010),
    /**
     * <code>GAMESERVER_QUER_FISHSCORE = 8011;</code>
     *
     * <pre>
     * 查询用户鱼粉
     * </pre>
     */
    GAMESERVER_QUER_FISHSCORE(111, 8011),
    /**
     * <code>GAMESERVER_PUSHFISH = 8500;</code>
     *
     * <pre>
     * 推送普通鱼的命令
     * </pre>
     */
    GAMESERVER_PUSHFISH(112, 8500),
    /**
     * <code>GAMESERVER_FISHFIRE = 8501;</code>
     *
     * <pre>
     * 开火命令
     * </pre>
     */
    GAMESERVER_FISHFIRE(113, 8501),
    /**
     * <code>GAMESERVER_FISHFIREOTHER = 8502;</code>
     *
     * <pre>
     * 想其他玩家推送你的子弹消息
     * </pre>
     */
    GAMESERVER_FISHFIREOTHER(114, 8502),
    /**
     * <code>GAMESERVER_FISHLOCKFISH = 8503;</code>
     *
     * <pre>
     * 锁定鱼的命令
     * </pre>
     */
    GAMESERVER_FISHLOCKFISH(115, 8503),
    /**
     * <code>GAMESERVER_FISHLOCKFISHOTHER = 8504;</code>
     *
     * <pre>
     * 向其他玩家推送 你的锁定鱼的
     * </pre>
     */
    GAMESERVER_FISHLOCKFISHOTHER(116, 8504),
    /**
     * <code>GAMESERVER_FISHCATCHFISH = 8505;</code>
     *
     * <pre>
     * 发送抓鱼命令
     * </pre>
     */
    GAMESERVER_FISHCATCHFISH(117, 8505),
    /**
     * <code>GAMESERVER_FISHCATCHFISHOTHER = 8506;</code>
     *
     * <pre>
     * 向其他玩家推送你碰到鱼的命令
     * </pre>
     */
    GAMESERVER_FISHCATCHFISHOTHER(118, 8506),
    /**
     * <code>GAMESERVER_FISHCHANGECANNON = 8508;</code>
     *
     * <pre>
     * 变炮
     * </pre>
     */
    GAMESERVER_FISHCHANGECANNON(119, 8508),
    /**
     * <code>GAMESERVER_FISHCHANGECANNONOTHER = 8509;</code>
     *
     * <pre>
     * 想其他玩家推送你的变炮消息
     * </pre>
     */
    GAMESERVER_FISHCHANGECANNONOTHER(120, 8509),
    /**
     * <code>GAMESERVER_PUSHFISHONEARRAY = 8510;</code>
     *
     * <pre>
     * 推送1号鱼阵信息
     * </pre>
     */
    GAMESERVER_PUSHFISHONEARRAY(121, 8510),
    /**
     * <code>GAMESERVER_PUSHCHANGESCENE = 8511;</code>
     *
     * <pre>
     * 推送  场景切换
     * </pre>
     */
    GAMESERVER_PUSHCHANGESCENE(122, 8511),
    /**
     * <code>GAMESERVER_PLAYERCOUNT = 8513;</code>
     *
     * <pre>
     *游戏服务器向协调推送最新在线玩家人数
     * </pre>
     */
    GAMESERVER_PLAYERCOUNT(123, 8513),
    /**
     * <code>GAMESERVER_FISHCATCHSPEFISH = 8514;</code>
     *
     * <pre>
     * 发送特殊抓鱼命令
     * </pre>
     */
    GAMESERVER_FISHCATCHSPEFISH(124, 8514),
    /**
     * <code>GAMESERVER_FISHCATCHFISHSPEOTHER = 8515;</code>
     *
     * <pre>
     * 向其他玩家推送你碰到鱼的命令
     * </pre>
     */
    GAMESERVER_FISHCATCHFISHSPEOTHER(125, 8515),
    /**
     * <code>GAMESERVER_ENERGYCANNO = 8516;</code>
     *
     * <pre>
     * 能量炮
     * </pre>
     */
    GAMESERVER_ENERGYCANNO(126, 8516),
    /**
     * <code>GAMESERVER_MATCHRESULT = 8520;</code>
     *
     * <pre>
     * 比赛结果信息
     * </pre>
     */
    GAMESERVER_MATCHRESULT(127, 8520),
    /**
     * <code>GAMESERVER_MATCHRANKRESULT = 8521;</code>
     *
     * <pre>
     * 比赛名次信息
     * </pre>
     */
    GAMESERVER_MATCHRANKRESULT(128, 8521),
    /**
     * <code>GAMESERVER_ONLINE_REWARD = 8522;</code>
     *
     * <pre>
     * 当前玩家领取奖励情况
     * </pre>
     */
    GAMESERVER_ONLINE_REWARD(129, 8522),
    /**
     * <code>GAMESERVER_ONLINE_RECEIVE_REWARD = 8523;</code>
     *
     * <pre>
     * 用户点击领取奖励
     * </pre>
     */
    GAMESERVER_ONLINE_RECEIVE_REWARD(130, 8523),
    /**
     * <code>GAMESERVER_TASK = 8524;</code>
     *
     * <pre>
     * 用户获取任务接口
     * </pre>
     */
    GAMESERVER_TASK(131, 8524),
    /**
     * <code>GAMESERVER_REFE_TASK = 8525;</code>
     *
     * <pre>
     *用户刷新任务接口
     * </pre>
     */
    GAMESERVER_REFE_TASK(132, 8525),
    /**
     * <code>GAMESERVER_TAKE_TASK = 8526;</code>
     *
     * <pre>
     *用户领取任务
     * </pre>
     */
    GAMESERVER_TAKE_TASK(133, 8526),
    /**
     * <code>GAMESERVER_TAKE_TASK_REWARD = 8527;</code>
     *
     * <pre>
     * 用户领取任务奖励
     * </pre>
     */
    GAMESERVER_TAKE_TASK_REWARD(134, 8527),
    /**
     * <code>GAMESERVER_TASK_COUNT_REF = 8528;</code>
     *
     * <pre>
     * 用户任务完成度刷新
     * </pre>
     */
    GAMESERVER_TASK_COUNT_REF(135, 8528),
    /**
     * <code>GAMESERVER_TOTAL_TASK_REF = 8529;</code>
     *
     * <pre>
     * 零点任务已完成总数量刷新
     * </pre>
     */
    GAMESERVER_TOTAL_TASK_REF(136, 8529),
    /**
     * <code>GAMESERVER_PROPDROP = 8530;</code>
     *
     * <pre>
     * 获取道具
     * </pre>
     */
    GAMESERVER_PROPDROP(137, 8530),
    /**
     * <code>GAMESERVER_ARENAPRIZE = 8531;</code>
     *
     * <pre>
     * 获取积分奖励列表
     * </pre>
     */
    GAMESERVER_ARENAPRIZE(138, 8531),
    /**
     * <code>GAMESERVER_ARENATAKE_PRIZE = 8532;</code>
     *
     * <pre>
     *领取积分奖励
     * </pre>
     */
    GAMESERVER_ARENATAKE_PRIZE(139, 8532),
    /**
     * <code>GAMESERVER_FISH_TIPS = 8533;</code>
     *
     * <pre>
     *鱼的提示语
     * </pre>
     */
    GAMESERVER_FISH_TIPS(140, 8533),
    /**
     * <code>COORDINATIONSERVER_ROOMINFO = 4000;</code>
     *
     * <pre>
     *协调服务器命令
     * </pre>
     */
    COORDINATIONSERVER_ROOMINFO(141, 4000),
    /**
     * <code>COORDINATIONSERVER_ROOMCOUNT = 4001;</code>
     *
     * <pre>
     * 协调推送过来的 房间人数信息
     * </pre>
     */
    COORDINATIONSERVER_ROOMCOUNT(142, 4001),
    /**
     * <code>COORDINATIONSERVER_REMOVE_ROOMINFO = 4002;</code>
     *
     * <pre>
     * 协调推送的删除房间信息
     * </pre>
     */
    COORDINATIONSERVER_REMOVE_ROOMINFO(143, 4002),
    /**
     * <code>COORDINATIONSERVER_SERVER_MESSAGE = 4003;</code>
     *
     * <pre>
     *  其他服务器给协调放聊天信息或者系统消息
     * </pre>
     */
    COORDINATIONSERVER_SERVER_MESSAGE(144, 4003),
    /**
     * <code>COORDINATIONSERVER_ROOMLIST = 4004;</code>
     *
     * <pre>
     * 想协调服务器请求当前所有的服务
     * </pre>
     */
    COORDINATIONSERVER_ROOMLIST(145, 4004),
    /**
     * <code>COORDINATIONSERVER_PLAYERCOUNT = 4005;</code>
     *
     * <pre>
     * 请求连接协调的游戏服务器上的在线人数
     * </pre>
     */
    COORDINATIONSERVER_PLAYERCOUNT(146, 4005),
    /**
     * <code>COORDINATIONSERVER_STOP = 4006;</code>
     *
     * <pre>
     * 鍋滄湇鍛戒护
     * </pre>
     */
    COORDINATIONSERVER_STOP(147, 4006),
    /**
     * <code>COORDINATIONSERVER_SEARCHROOMSTOCK = 4007;</code>
     *
     * <pre>
     *查询房间的库存
     * </pre>
     */
    COORDINATIONSERVER_SEARCHROOMSTOCK(148, 4007),
    /**
     * <code>COORDINATIONSERVER_SEARCHROOMSTOCKRESP = 4008;</code>
     *
     * <pre>
     *查询房间库存的值
     * </pre>
     */
    COORDINATIONSERVER_SEARCHROOMSTOCKRESP(149, 4008),
    /**
     * <code>COORDINATIONSERVER_UPDATEROOMSTOCK = 4009;</code>
     *
     * <pre>
     *修改库存值
     * </pre>
     */
    COORDINATIONSERVER_UPDATEROOMSTOCK(150, 4009),
    /**
     * <code>COORDINATIONSERVER_UPDATEROOMSTOCKRESP = 4010;</code>
     *
     * <pre>
     *修改库存成功
     * </pre>
     */
    COORDINATIONSERVER_UPDATEROOMSTOCKRESP(151, 4010),
    /**
     * <code>COORDINATIONSERVER_KICKOUTUSER = 4011;</code>
     *
     * <pre>
     * 强制踢出在线玩家
     * </pre>
     */
    COORDINATIONSERVER_KICKOUTUSER(152, 4011),
    /**
     * <code>COORDINATIONSERVER_SYNCPROFILE = 4012;</code>
     *
     * <pre>
     * 同步配置文件
     * </pre>
     */
    COORDINATIONSERVER_SYNCPROFILE(153, 4012),
    /**
     * <code>COORDINATIONSERVER_KICKLOGINUSER = 4013;</code>
     *
     * <pre>
     * 踢出别的服务器上的当前玩家
     * </pre>
     */
    COORDINATIONSERVER_KICKLOGINUSER(154, 4013),
    /**
     * <code>COORDINATIONSERVER_SYNCCONF = 4014;</code>
     *
     * <pre>
     * 同步配置文件 4012
     * </pre>
     */
    COORDINATIONSERVER_SYNCCONF(155, 4014),
    /**
     * <code>LOGIN_FETCH_VERIFY_CODE = 825;</code>
     *
     * <pre>
     *获取验证码
     * </pre>
     */
    LOGIN_FETCH_VERIFY_CODE(156, 825),
    /**
     * <code>LOGIN_ACCOUNTS_BIND = 826;</code>
     *
     * <pre>
     *绑定账号
     * </pre>
     */
    LOGIN_ACCOUNTS_BIND(157, 826),
    /**
     * <code>LOGIN_ACCOUNTS_DEBIND = 827;</code>
     *
     * <pre>
     *解绑账号
     * </pre>
     */
    LOGIN_ACCOUNTS_DEBIND(158, 827),
    /**
     * <code>LOGIN_FETCH_PLAYER_INFO = 828;</code>
     *
     * <pre>
     *获取玩家信息
     * </pre>
     */
    LOGIN_FETCH_PLAYER_INFO(159, 828),
    /**
     * <code>LOGIN_PACK_ITEM_OPT = 830;</code>
     *
     * <pre>
     *背包操作
     * </pre>
     */
    LOGIN_PACK_ITEM_OPT(160, 830),
    /**
     * <code>LOGIN_PACK_ITEM_RELOAD = 831;</code>
     *
     * <pre>
     *重新拉取背包操作
     * </pre>
     */
    LOGIN_PACK_ITEM_RELOAD(161, 831),
    /**
     * <code>LOGIN_FESTIVAL_PRIZE_CHECK = 832;</code>
     *
     * <pre>
     *检查是可以领取节日奖励
     * </pre>
     */
    LOGIN_FESTIVAL_PRIZE_CHECK(162, 832),
    /**
     * <code>LOGIN_FESTIVAL_PRIZE_GET = 833;</code>
     *
     * <pre>
     *领取节日奖励
     * </pre>
     */
    LOGIN_FESTIVAL_PRIZE_GET(163, 833),
    /**
     * <code>LOGIN_FETCH_UPLOAD_TOKEN = 834;</code>
     *
     * <pre>
     *获取上传token
     * </pre>
     */
    LOGIN_FETCH_UPLOAD_TOKEN(164, 834),
    /**
     * <code>GAME_MATCH_QUERY_START_TIME = 840;</code>
     *
     * <pre>
     *获取比赛开始时间
     * </pre>
     */
    GAME_MATCH_QUERY_START_TIME(165, 840),
    /**
     * <code>GAME_SERVER_MATCH_WIN_SCORE = 841;</code>
     *
     * <pre>
     *广播名次和分数
     * </pre>
     */
    GAME_SERVER_MATCH_WIN_SCORE(166, 841),
    /**
     * <code>GAME_SERVER_MATCH_OVER_SCORE = 842;</code>
     *
     * <pre>
     *游戏结束时广播成绩
     * </pre>
     */
    GAME_SERVER_MATCH_OVER_SCORE(167, 842),
    /**
     * <code>GAME_SERVER_REGISTER_TO_MATCH_CMD = 843;</code>
     *
     * <pre>
     *注册游戏服到MatchServer
     * </pre>
     */
    GAME_SERVER_REGISTER_TO_MATCH_CMD(168, 843),
    /**
     * <code>GAME_SERVER_MATCH_SIT_DOWN = 844;</code>
     *
     * <pre>
     *比赛玩家坐下
     * </pre>
     */
    GAME_SERVER_MATCH_SIT_DOWN(169, 844),
    /**
     * <code>LOGIN_SERVER_HD_GET_INFO = 845;</code>
     *
     * <pre>
     *获取活动信息
     * </pre>
     */
    LOGIN_SERVER_HD_GET_INFO(170, 845),
    /**
     * <code>LOGIN_SERVER_HD_OPEN = 846;</code>
     *
     * <pre>
     *开活动物品
     * </pre>
     */
    LOGIN_SERVER_HD_OPEN(171, 846),
    /**
     * <code>LOGIN_SERVER_RAND_INFO = 847;</code>
     *
     * <pre>
     *获取活动排行
     * </pre>
     */
    LOGIN_SERVER_RAND_INFO(172, 847),
    /**
     * <code>LOGIN_SERVER_RED_POINT = 848;</code>
     *
     * <pre>
     *推送红点信息
     * </pre>
     */
    LOGIN_SERVER_RED_POINT(173, 848),
    /**
     * <code>LOGIN_SERVER_CLIENT_NEED = 849;</code>
     *
     * <pre>
     *推送客户端需要配置信息
     * </pre>
     */
    LOGIN_SERVER_CLIENT_NEED(174, 849),
    /**
     * <code>LOGIN_SERVER_ACTIVITY_QUERY = 850;</code>
     *
     * <pre>
     *查询vip可兑换的豆
     * </pre>
     */
    LOGIN_SERVER_ACTIVITY_QUERY(175, 850),
    /**
     * <code>LOGIN_SERVER_ACTIVITY_EXECUTE = 851;</code>
     *
     * <pre>
     *领取vip奖励
     * </pre>
     */
    LOGIN_SERVER_ACTIVITY_EXECUTE(176, 851),
    /**
     * <code>LOGIN_SERVER_ACTIVITY_LIST = 852;</code>
     */
    LOGIN_SERVER_ACTIVITY_LIST(177, 852),
    /**
     * <code>LOGIN_SERVER_CHARGE_TOOL_AWARD = 853;</code>
     */
    LOGIN_SERVER_CHARGE_TOOL_AWARD(178, 853),
    /**
     * <code>LOGIN_SERVER_MAIL_LIST = 860;</code>
     *
     * <pre>
     *请求邮件列表
     * </pre>
     */
    LOGIN_SERVER_MAIL_LIST(179, 860),
    /**
     * <code>LOGIN_SERVER_MAILS = 861;</code>
     *
     * <pre>
     *请求邮件内容
     * </pre>
     */
    LOGIN_SERVER_MAILS(180, 861),
    /**
     * <code>LOGIN_SERVER_OPT_MAIL = 862;</code>
     *
     * <pre>
     *对邮件进行操作
     * </pre>
     */
    LOGIN_SERVER_OPT_MAIL(181, 862),
    /**
     * <code>LOGIN_SERVER_ADVISE_CLIENT_MAIL = 863;</code>
     *
     * <pre>
     *通知客户端拉取邮件
     * </pre>
     */
    LOGIN_SERVER_ADVISE_CLIENT_MAIL(182, 863),
    /**
     * <code>LOGIN_SERVER_VIP_SHOW = 864;</code>
     *
     * <pre>
     *vip展示
     * </pre>
     */
    LOGIN_SERVER_VIP_SHOW(183, 864),
    /**
     * <code>LOGIN_SERVER_VIP_CHARGE = 865;</code>
     *
     * <pre>
     *获取vip充值
     * </pre>
     */
    LOGIN_SERVER_VIP_CHARGE(184, 865),
    /**
     * <code>LOGIN_SERVER_GET_CHARGE_LIST = 866;</code>
     *
     * <pre>
     *获取充值列表
     * </pre>
     */
    LOGIN_SERVER_GET_CHARGE_LIST(185, 866),
    /**
     * <code>LOGIN_SERVER_MATCH_TZ_BAOMING = 867;</code>
     *
     * <pre>
     *挑战赛报名
     * </pre>
     */
    LOGIN_SERVER_MATCH_TZ_BAOMING(186, 867),
    /**
     * <code>LOGIN_SERVER_TASK_QUERY = 870;</code>
     *
     * <pre>
     *查询任务进度
     * </pre>
     */
    LOGIN_SERVER_TASK_QUERY(187, 870),
    /**
     * <code>LOGIN_SERVER_TASK_RECV = 871;</code>
     *
     * <pre>
     *领取任务奖励
     * </pre>
     */
    LOGIN_SERVER_TASK_RECV(188, 871),
    /**
     * <code>LOGIN_SERVER_LGDB_QUERY = 8601;</code>
     *
     * <pre>
     *龙宫夺宝加载信息CMD
     * </pre>
     */
    LOGIN_SERVER_LGDB_QUERY(189, 8601),
    /**
     * <code>LOGIN_SERVER_LGDB_RESET = 8602;</code>
     *
     * <pre>
     *龙宫夺宝刷新转盘
     * </pre>
     */
    LOGIN_SERVER_LGDB_RESET(190, 8602),
    /**
     * <code>LOGIN_SERVER_LGDB_RUN = 8603;</code>
     *
     * <pre>
     *龙宫夺宝抽奖
     * </pre>
     */
    LOGIN_SERVER_LGDB_RUN(191, 8603),
    /**
     * <code>LOGIN_SERVER_LGDB_RECV = 8604;</code>
     *
     * <pre>
     *龙宫夺宝领排行榜奖励
     * </pre>
     */
    LOGIN_SERVER_LGDB_RECV(192, 8604),
    /**
     * <code>LOGIN_SERVER_LGDB_HISTORY = 8605;</code>
     *
     * <pre>
     *龙宫夺宝抽奖历史记录
     * </pre>
     */
    LOGIN_SERVER_LGDB_HISTORY(193, 8605),
    /**
     * <code>LOGIN_SERVER_LGDB_RANK = 8606;</code>
     *
     * <pre>
     *查询龙宫夺宝排行榜信息
     * </pre>
     */
    LOGIN_SERVER_LGDB_RANK(194, 8606),
    /**
     * <code>LOGIN_SERVER_LGDB_PUSH_SUPER_AWARD = 8607;</code>
     *
     * <pre>
     *有人拿到大奖后,推送到客户端
     * </pre>
     */
    LOGIN_SERVER_LGDB_PUSH_SUPER_AWARD(195, 8607),
    /**
     * <code>GAME_SERVER_RECONNECT_SEND_INFO = 8608;</code>
     *
     * <pre>
     *客户端重连到新的loginserver之后,发送其最新位置给游戏服务器
     * </pre>
     */
    GAME_SERVER_RECONNECT_SEND_INFO(196, 8608),
    /**
     * <code>GAME_SERVER_TZ_STAGE_INFO = 8700;</code>
     *
     * <pre>
     *挑战赛阶段信息
     * </pre>
     */
    GAME_SERVER_TZ_STAGE_INFO(197, 8700),
    /**
     * <code>GAME_SERVER_TZ_SCORE_ENOUGH = 8701;</code>
     *
     * <pre>
     *挑战赛分数已足
     * </pre>
     */
    GAME_SERVER_TZ_SCORE_ENOUGH(198, 8701),
    /**
     * <code>GAME_SERVER_TZ_OVER_OPT = 8702;</code>
     *
     * <pre>
     *挑战赛分数已足
     * </pre>
     */
    GAME_SERVER_TZ_OVER_OPT(199, 8702),
    /**
     * <code>GAME_SERVER_GIVEUP = 8703;</code>
     *
     * <pre>
     * 放弃比赛
     * </pre>
     */
    GAME_SERVER_GIVEUP(200, 8703),
    /**
     * <code>LOGIN_SERVER_MAILS_OVER = 8610;</code>
     *
     * <pre>
     *邮件发送结束
     * </pre>
     */
    LOGIN_SERVER_MAILS_OVER(201, 8610),
    /**
     * <code>LOGIN_SERVER_SEND_LUA_VERSION = 900;</code>
     *
     * <pre>
     *发送lua版本
     * </pre>
     */
    LOGIN_SERVER_SEND_LUA_VERSION(202, 900),
    /**
     * <code>LOGIN_PACK_QUERY_COMPOSE = 920;</code>
     */
    LOGIN_PACK_QUERY_COMPOSE(203, 920),
    /**
     * <code>LOGIN_PACK_DO_COMPOSE = 921;</code>
     */
    LOGIN_PACK_DO_COMPOSE(204, 921),
    /**
     * <code>LOGIN_SERVER_ARENA_DAY_RANK = 922;</code>
     */
    LOGIN_SERVER_ARENA_DAY_RANK(205, 922),
    /**
     * <code>LOGIN_SERVER_ARENA_WEEK_RANK = 923;</code>
     */
    LOGIN_SERVER_ARENA_WEEK_RANK(206, 923),
    /**
     * <code>LOGIN_SERVER_ARENA_README = 924;</code>
     */
    LOGIN_SERVER_ARENA_README(207, 924),
    /**
     * <code>LOGIN_ARENA_UNLOCK = 1000;</code>
     *
     * <pre>
     *解锁竞技场
     * </pre>
     */
    LOGIN_ARENA_UNLOCK(208, 1000),
    /**
     * <code>LOGIN_ARENA_QUERY_BOARD = 1001;</code>
     *
     * <pre>
     *请求竞技场board
     * </pre>
     */
    LOGIN_ARENA_QUERY_BOARD(209, 1001),
    /**
     * <code>LOGIN_ARENA_SIGN = 1002;</code>
     *
     * <pre>
     *竞技场报名
     * </pre>
     */
    LOGIN_ARENA_SIGN(210, 1002),
    /**
     * <code>LOGIN_ARENA_REPORT = 1003;</code>
     *
     * <pre>
     *竞技场奖状
     * </pre>
     */
    LOGIN_ARENA_REPORT(211, 1003),
    /**
     * <code>LOGIN_ARENA_FUNC_STATUS = 1004;</code>
     */
    LOGIN_ARENA_FUNC_STATUS(212, 1004),
    /**
     * <code>LOGIN_ARENA_UNLOCK_CHECK = 1005;</code>
     */
    LOGIN_ARENA_UNLOCK_CHECK(213, 1005),
    /**
     * <code>LOGIN_ARENA_QUERY_UPPER_BOARD = 1009;</code>
     */
    LOGIN_ARENA_QUERY_UPPER_BOARD(214, 1009),
    /**
     * <code>LOGIN_FREE_GOLD_FETCH_INFO = 1006;</code>
     */
    LOGIN_FREE_GOLD_FETCH_INFO(215, 1006),
    /**
     * <code>LOGIN_FREE_GOLD_INCOME_LIST = 1007;</code>
     */
    LOGIN_FREE_GOLD_INCOME_LIST(216, 1007),
    /**
     * <code>LOGIN_FREE_GOLD_EXCHANGE = 1008;</code>
     */
    LOGIN_FREE_GOLD_EXCHANGE(217, 1008),
    /**
     * <code>LOGIN_FREE_GOLD_README = 1010;</code>
     */
    LOGIN_FREE_GOLD_README(218, 1010),
    /**
     * <code>REFRESH = 10000;</code>
     */
    REFRESH(219, 10000),
    /**
     * <code>CREATE_ORDER = 600;</code>
     *
     * <pre>
     *创建订单
     * </pre>
     */
    CREATE_ORDER(220, 600),
    /**
     * <code>QUERY_ORDER = 601;</code>
     *
     * <pre>
     *查询订单
     * </pre>
     */
    QUERY_ORDER(221, 601),
    /**
     * <code>PUT_CLIENT_IP = 999;</code>
     *
     * <pre>
     *推送客户端IP
     * </pre>
     */
    PUT_CLIENT_IP(222, 999),
    ;

    /**
     * <code>SERVER_ERROR = 5000;</code>
     *
     * <pre>
     *错误命令
     * </pre>
     */
    public static final int SERVER_ERROR_VALUE = 5000;
    /**
     * <code>LOGINSERVER_LOGIN_BYPHONE = 99;</code>
     *
     * <pre>
     *手机登陆登陆
     * </pre>
     */
    public static final int LOGINSERVER_LOGIN_BYPHONE_VALUE = 99;
    /**
     * <code>LOGINSERVER_LOGIN = 100;</code>
     *
     * <pre>
     *登陆服务器命令
     * </pre>
     */
    public static final int LOGINSERVER_LOGIN_VALUE = 100;
    /**
     * <code>LOGINSERVER_REGIST = 101;</code>
     *
     * <pre>
     *注册
     * </pre>
     */
    public static final int LOGINSERVER_REGIST_VALUE = 101;
    /**
     * <code>GAMEROOM_LIST = 300;</code>
     *
     * <pre>
     * 获取房间列表命令
     * </pre>
     */
    public static final int GAMEROOM_LIST_VALUE = 300;
    /**
     * <code>GAMETYPE_LIST = 301;</code>
     *
     * <pre>
     * 游戏类型命令
     * </pre>
     */
    public static final int GAMETYPE_LIST_VALUE = 301;
    /**
     * <code>GAMEINFOOFGAMETYPE = 302;</code>
     *
     * <pre>
     *游戏信息
     * </pre>
     */
    public static final int GAMEINFOOFGAMETYPE_VALUE = 302;
    /**
     * <code>GAMEROOMTYPE_LIST = 303;</code>
     *
     * <pre>
     *游戏房间类型
     * </pre>
     */
    public static final int GAMEROOMTYPE_LIST_VALUE = 303;
    /**
     * <code>GAMEROOMTYPE = 304;</code>
     *
     * <pre>
     *游戏房间分类
     * </pre>
     */
    public static final int GAMEROOMTYPE_VALUE = 304;
    /**
     * <code>USERLOCKMACHINE = 305;</code>
     *
     * <pre>
     *用户锁定本机
     * </pre>
     */
    public static final int USERLOCKMACHINE_VALUE = 305;
    /**
     * <code>LOGINSERVER_SYSMESG = 306;</code>
     *
     * <pre>
     * 系统弹出框消息
     * </pre>
     */
    public static final int LOGINSERVER_SYSMESG_VALUE = 306;
    /**
     * <code>LOGINSERVER_PUBLIC_SYSMESG = 307;</code>
     *
     * <pre>
     *通用系统消息
     * </pre>
     */
    public static final int LOGINSERVER_PUBLIC_SYSMESG_VALUE = 307;
    /**
     * <code>BANK_RECORD_QUERY = 400;</code>
     *
     * <pre>
     *公共命令
     * </pre>
     */
    public static final int BANK_RECORD_QUERY_VALUE = 400;
    /**
     * <code>BANK_QUERY = 401;</code>
     *
     * <pre>
     * 银行信息查询命令
     * </pre>
     */
    public static final int BANK_QUERY_VALUE = 401;
    /**
     * <code>BANK_SAVE = 402;</code>
     *
     * <pre>
     *存游戏币
     * </pre>
     */
    public static final int BANK_SAVE_VALUE = 402;
    /**
     * <code>BANK_TAKE = 403;</code>
     *
     * <pre>
     *提取游戏币
     * </pre>
     */
    public static final int BANK_TAKE_VALUE = 403;
    /**
     * <code>BANK_TRANSFER = 404;</code>
     *
     * <pre>
     *游戏币转账
     * </pre>
     */
    public static final int BANK_TRANSFER_VALUE = 404;
    /**
     * <code>BANK_EXCHANGE = 405;</code>
     *
     * <pre>
     *充值金币兑换游戏币
     * </pre>
     */
    public static final int BANK_EXCHANGE_VALUE = 405;
    /**
     * <code>BANK_PROP_TO_SCORE = 406;</code>
     *
     * <pre>
     *奖券转换为幸运豆
     * </pre>
     */
    public static final int BANK_PROP_TO_SCORE_VALUE = 406;
    /**
     * <code>TAKE_GOLD = 407;</code>
     *
     * <pre>
     *救济金自动领取
     * </pre>
     */
    public static final int TAKE_GOLD_VALUE = 407;
    /**
     * <code>TIME_SYN = 408;</code>
     *
     * <pre>
     * 同步时间
     * </pre>
     */
    public static final int TIME_SYN_VALUE = 408;
    /**
     * <code>GET_GOODS_VALUE = 409;</code>
     *
     * <pre>
     * 获取商品价值
     * </pre>
     */
    public static final int GET_GOODS_VALUE_VALUE = 409;
    /**
     * <code>GIVE_ROSE = 410;</code>
     *
     * <pre>
     * 赠送道具
     * </pre>
     */
    public static final int GIVE_ROSE_VALUE = 410;
    /**
     * <code>GIVE_ROSE_OTHER = 411;</code>
     *
     * <pre>
     * 赠送人获取奖品
     * </pre>
     */
    public static final int GIVE_ROSE_OTHER_VALUE = 411;
    /**
     * <code>GAMEPAYOK = 412;</code>
     *
     * <pre>
     * 游戏支付成功
     * </pre>
     */
    public static final int GAMEPAYOK_VALUE = 412;
    /**
     * <code>USERCONTROL = 413;</code>
     *
     * <pre>
     * 用户AB 控制
     * </pre>
     */
    public static final int USERCONTROL_VALUE = 413;
    /**
     * <code>USERINVITEDSCORECMD = 414;</code>
     *
     * <pre>
     *用户被邀请(用户使用邀请码兑换奖励)
     * </pre>
     */
    public static final int USERINVITEDSCORECMD_VALUE = 414;
    /**
     * <code>INVITEUSERSCORECMD = 415;</code>
     *
     * <pre>
     *邀请用户(用户邀请到一定数量玩家时领取对应档次的奖励)
     * </pre>
     */
    public static final int INVITEUSERSCORECMD_VALUE = 415;
    /**
     * <code>USER_SEND_RADPACKET = 416;</code>
     *
     * <pre>
     *用户封红包
     * </pre>
     */
    public static final int USER_SEND_RADPACKET_VALUE = 416;
    /**
     * <code>USER_GET_RADPACKET = 417;</code>
     *
     * <pre>
     *用户获得红包
     * </pre>
     */
    public static final int USER_GET_RADPACKET_VALUE = 417;
    /**
     * <code>INVITEUSERCOUNTCMD = 418;</code>
     *
     * <pre>
     *已经邀请过的用户数量(用户查询邀请多的用户)
     * </pre>
     */
    public static final int INVITEUSERCOUNTCMD_VALUE = 418;
    /**
     * <code>INVITEORSHARECOUNT = 419;</code>
     *
     * <pre>
     *用户查询分享，邀请到的玩家数量
     * </pre>
     */
    public static final int INVITEORSHARECOUNT_VALUE = 419;
    /**
     * <code>INVITEORSHARE = 420;</code>
     *
     * <pre>
     *用户分享，邀请领取奖励
     * </pre>
     */
    public static final int INVITEORSHARE_VALUE = 420;
    /**
     * <code>TRANS_STR_IN = 421;</code>
     *
     * <pre>
     *传递字符串给登录服务器
     * </pre>
     */
    public static final int TRANS_STR_IN_VALUE = 421;
    /**
     * <code>SHARE_QUERY = 422;</code>
     *
     * <pre>
     *分享赚取积分,已经分享积分开宝箱子,add by 2016.05.14
     * </pre>
     */
    public static final int SHARE_QUERY_VALUE = 422;
    /**
     * <code>SHARE_SUCCESS_NOTICE = 423;</code>
     *
     * <pre>
     *用户分享成功后通知服务器邀请领取奖励,ShareSuccessReq-&gt;ShareSuccessResp
     * </pre>
     */
    public static final int SHARE_SUCCESS_NOTICE_VALUE = 423;
    /**
     * <code>SHARE_OPEN_BOX = 424;</code>
     *
     * <pre>
     *开积分宝箱,ShareOpenBoxReq-&gt;ShareOpenBoxResp
     * </pre>
     */
    public static final int SHARE_OPEN_BOX_VALUE = 424;
    /**
     * <code>SHARE_QUERY_DETAIL = 425;</code>
     *
     * <pre>
     *查询积分贡献榜,empty-&gt;ShareScoreDetailResp
     * </pre>
     */
    public static final int SHARE_QUERY_DETAIL_VALUE = 425;
    /**
     * <code>PRESENT_QUERY = 430;</code>
     *
     * <pre>
     *银行赠送,add by 2016.05.25
     * </pre>
     */
    public static final int PRESENT_QUERY_VALUE = 430;
    /**
     * <code>PRESENT_GOLD = 431;</code>
     *
     * <pre>
     *赠送金币，PresentGoldReq-&gt;PresentQueryResp
     * </pre>
     */
    public static final int PRESENT_GOLD_VALUE = 431;
    /**
     * <code>BULLSCORE_USE_LIST = 433;</code>
     *
     * <pre>
     *add by 2016.06.04
     * </pre>
     */
    public static final int BULLSCORE_USE_LIST_VALUE = 433;
    /**
     * <code>BULLSCORE_USE = 434;</code>
     *
     * <pre>
     *券兑换,BullScoreUseReq,BullScoreUseResp
     * </pre>
     */
    public static final int BULLSCORE_USE_VALUE = 434;
    /**
     * <code>BULLSCORE_USE_HISTORY = 435;</code>
     *
     * <pre>
     *牛券兑换明细,BullScoreUseHistoryReq,BullScoreUseHistoryResp
     * </pre>
     */
    public static final int BULLSCORE_USE_HISTORY_VALUE = 435;
    /**
     * <code>PAY_IOS_RECEIPRT = 440;</code>
     *
     * <pre>
     *add by 2016.08.06
     * </pre>
     */
    public static final int PAY_IOS_RECEIPRT_VALUE = 440;
    /**
     * <code>PAY_INDEX = 441;</code>
     *
     * <pre>
     *add by 2016.08.23
     * </pre>
     */
    public static final int PAY_INDEX_VALUE = 441;
    /**
     * <code>USERINFO_GETCOMMONINFO = 800;</code>
     *
     * <pre>
     *用户中心命令
     * </pre>
     */
    public static final int USERINFO_GETCOMMONINFO_VALUE = 800;
    /**
     * <code>USERINFO_GETDETAILINFO = 801;</code>
     *
     * <pre>
     *获取用户的详细信息
     * </pre>
     */
    public static final int USERINFO_GETDETAILINFO_VALUE = 801;
    /**
     * <code>USERINFO_UPDATE_LOGINPWD = 802;</code>
     *
     * <pre>
     *修改用户的登录密码
     * </pre>
     */
    public static final int USERINFO_UPDATE_LOGINPWD_VALUE = 802;
    /**
     * <code>USERINFO_UPDATE_INSUREPWD = 803;</code>
     *
     * <pre>
     *修改用户的保险柜密码
     * </pre>
     */
    public static final int USERINFO_UPDATE_INSUREPWD_VALUE = 803;
    /**
     * <code>USERINFO_UPDATE_COMMONINFO = 804;</code>
     *
     * <pre>
     *修改用户的普通信息
     * </pre>
     */
    public static final int USERINFO_UPDATE_COMMONINFO_VALUE = 804;
    /**
     * <code>USERINFO_UPDATE_DETAILINFO = 805;</code>
     *
     * <pre>
     *修改用户的详细信息
     * </pre>
     */
    public static final int USERINFO_UPDATE_DETAILINFO_VALUE = 805;
    /**
     * <code>USERINFO_QMFD_JOINGAME = 806;</code>
     *
     * <pre>
     *参加"全民福袋"活动
     * </pre>
     */
    public static final int USERINFO_QMFD_JOINGAME_VALUE = 806;
    /**
     * <code>USERINFO_QMFD_RANKING = 807;</code>
     *
     * <pre>
     *"全民福袋"活动单局排名
     * </pre>
     */
    public static final int USERINFO_QMFD_RANKING_VALUE = 807;
    /**
     * <code>USERINFO_QMFD_SETTLEMENT = 808;</code>
     *
     * <pre>
     *"全民福袋"活动单局结算
     * </pre>
     */
    public static final int USERINFO_QMFD_SETTLEMENT_VALUE = 808;
    /**
     * <code>USERINFO_QMFD_STARTUP = 809;</code>
     *
     * <pre>
     *向客户端推动"全民福袋"开始信息
     * </pre>
     */
    public static final int USERINFO_QMFD_STARTUP_VALUE = 809;
    /**
     * <code>USERINFO_ZZ_GET = 810;</code>
     *
     * <pre>
     * 得到粽子活动的信息
     * </pre>
     */
    public static final int USERINFO_ZZ_GET_VALUE = 810;
    /**
     * <code>USERINFO_ZZ_RANK = 811;</code>
     *
     * <pre>
     * 得到活动的排名信息
     * </pre>
     */
    public static final int USERINFO_ZZ_RANK_VALUE = 811;
    /**
     * <code>USERINFO_ZZ_OPEN = 812;</code>
     *
     * <pre>
     * 剥粽子的排名信息
     * </pre>
     */
    public static final int USERINFO_ZZ_OPEN_VALUE = 812;
    /**
     * <code>USERINFO_ZZ_BUY = 813;</code>
     *
     * <pre>
     * 买粽子
     * </pre>
     */
    public static final int USERINFO_ZZ_BUY_VALUE = 813;
    /**
     * <code>USERINFO_RANK_SHOW = 814;</code>
     *
     * <pre>
     *查看排行榜
     * </pre>
     */
    public static final int USERINFO_RANK_SHOW_VALUE = 814;
    /**
     * <code>USERINFO_RANK_THUMB_UP = 815;</code>
     *
     * <pre>
     *排行榜点赞
     * </pre>
     */
    public static final int USERINFO_RANK_THUMB_UP_VALUE = 815;
    /**
     * <code>USERINFO_RANK_RECV_AWARD = 816;</code>
     *
     * <pre>
     *排行榜领取奖励
     * </pre>
     */
    public static final int USERINFO_RANK_RECV_AWARD_VALUE = 816;
    /**
     * <code>LOGINSERVER_QIANDAO_INDEX = 819;</code>
     *
     * <pre>
     *签到加载信息
     * </pre>
     */
    public static final int LOGINSERVER_QIANDAO_INDEX_VALUE = 819;
    /**
     * <code>LOGINSERVER_QIANDAO = 820;</code>
     *
     * <pre>
     *签到
     * </pre>
     */
    public static final int LOGINSERVER_QIANDAO_VALUE = 820;
    /**
     * <code>LOGINSERVER_QIANDAO_RECV_TOTAL = 821;</code>
     *
     * <pre>
     *领取累计签到x天的奖励
     * </pre>
     */
    public static final int LOGINSERVER_QIANDAO_RECV_TOTAL_VALUE = 821;
    /**
     * <code>LOGINSERVER_QIANDAO_CHANGE_TIME = 822;</code>
     *
     * <pre>
     *累计签到设置当前第几天
     * </pre>
     */
    public static final int LOGINSERVER_QIANDAO_CHANGE_TIME_VALUE = 822;
    /**
     * <code>LOGINSERVER_MATCH_FETCH_ACT_LIST = 8301;</code>
     *
     * <pre>
     *拉取赛事活动列表
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_FETCH_ACT_LIST_VALUE = 8301;
    /**
     * <code>LOGINSERVER_MATCH_BAO_MING = 8302;</code>
     *
     * <pre>
     *报名参加比赛
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_BAO_MING_VALUE = 8302;
    /**
     * <code>LOGINSERVER_MATCH_CANCEL = 8303;</code>
     *
     * <pre>
     *取消参加比赛
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_CANCEL_VALUE = 8303;
    /**
     * <code>LOGINSERVER_MATCH_FETCH_TYPES = 8304;</code>
     *
     * <pre>
     *获取特定比赛类型的赛事列表
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_FETCH_TYPES_VALUE = 8304;
    /**
     * <code>LOGINSERVER_MATCH_FETCH_TYPE_DETAIL = 8305;</code>
     *
     * <pre>
     *点击五元话费场,打开详情框
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_FETCH_TYPE_DETAIL_VALUE = 8305;
    /**
     * <code>LOGINSERVER_MATCH_REFRESH_PERSON_COUNT = 8306;</code>
     *
     * <pre>
     *客户端定时刷新当前比赛报名人数
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_REFRESH_PERSON_COUNT_VALUE = 8306;
    /**
     * <code>LOGINSERVER_MATCH_BEGIN = 8307;</code>
     *
     * <pre>
     *服务器通知全部报了名的客户端比赛开始
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_BEGIN_VALUE = 8307;
    /**
     * <code>LOGINSERVER_MATCH_GIVEUP = 8308;</code>
     *
     * <pre>
     *比赛开始的命令推送给玩家后,玩家选择放弃按钮,不来参加比赛
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_GIVEUP_VALUE = 8308;
    /**
     * <code>LOGINSERVER_MATCH_BEGIN_PULL = 8309;</code>
     *
     * <pre>
     *玩家登陆时,推送已经开始的比赛
     * </pre>
     */
    public static final int LOGINSERVER_MATCH_BEGIN_PULL_VALUE = 8309;
    /**
     * <code>LOGIN_SERVER_CHAT_SEND = 8310;</code>
     *
     * <pre>
     *LOGIN聊天发送信息
     * </pre>
     */
    public static final int LOGIN_SERVER_CHAT_SEND_VALUE = 8310;
    /**
     * <code>LOGIN_SERVER_CHAT_RECEIVE = 8311;</code>
     *
     * <pre>
     *LOGIN聊天发送信息
     * </pre>
     */
    public static final int LOGIN_SERVER_CHAT_RECEIVE_VALUE = 8311;
    /**
     * <code>GAME_SERVER_CHAT_SEND = 8312;</code>
     *
     * <pre>
     *game聊天发送信息
     * </pre>
     */
    public static final int GAME_SERVER_CHAT_SEND_VALUE = 8312;
    /**
     * <code>GAME_SERVER_CHAT_RECEIVE = 8313;</code>
     *
     * <pre>
     *game聊天发送信息
     * </pre>
     */
    public static final int GAME_SERVER_CHAT_RECEIVE_VALUE = 8313;
    /**
     * <code>GAME_SERVER_REFRESH_USER_STATUS = 8314;</code>
     *
     * <pre>
     *后台禁言玩家后,hub通知游戏服务器更新状态
     * </pre>
     */
    public static final int GAME_SERVER_REFRESH_USER_STATUS_VALUE = 8314;
    /**
     * <code>GAME_SERVER_UPDATE_NOTICE_LIST = 8315;</code>
     *
     * <pre>
     *后台修改系统公告后,通知game server
     * </pre>
     */
    public static final int GAME_SERVER_UPDATE_NOTICE_LIST_VALUE = 8315;
    /**
     * <code>LOGIN_SERVER_CHAT_DLG_OPERATION = 8316;</code>
     *
     * <pre>
     *用户打开或者关闭聊天窗口
     * </pre>
     */
    public static final int LOGIN_SERVER_CHAT_DLG_OPERATION_VALUE = 8316;
    /**
     * <code>SERVER_REFRESH_SERVER_STATUS = 8317;</code>
     *
     * <pre>
     *hub通知游戏服务器更新状态
     * </pre>
     */
    public static final int SERVER_REFRESH_SERVER_STATUS_VALUE = 8317;
    /**
     * <code>LOGIN_SERVER_SUPER_CHARGE = 8318;</code>
     */
    public static final int LOGIN_SERVER_SUPER_CHARGE_VALUE = 8318;
    /**
     * <code>LOGIN_SERVER_MATCH_OL_COUNT = 8319;</code>
     */
    public static final int LOGIN_SERVER_MATCH_OL_COUNT_VALUE = 8319;
    /**
     * <code>LOGIN_GET_SCORE = 8320;</code>
     *
     * <pre>
     *登录领取幸运豆推送消息
     * </pre>
     */
    public static final int LOGIN_GET_SCORE_VALUE = 8320;
    /**
     * <code>GET_FREE_SCORE = 8321;</code>
     *
     * <pre>
     *从推送中领取幸运豆
     * </pre>
     */
    public static final int GET_FREE_SCORE_VALUE = 8321;
    /**
     * <code>GAMESERVER_LOGIN = 200;</code>
     *
     * <pre>
     *游戏服务器命令
     * </pre>
     */
    public static final int GAMESERVER_LOGIN_VALUE = 200;
    /**
     * <code>GAMESERVER_OTHERLOGIN = 201;</code>
     *
     * <pre>
     *其他玩家登陆成功
     * </pre>
     */
    public static final int GAMESERVER_OTHERLOGIN_VALUE = 201;
    /**
     * <code>GAMESERVER_LOGIN_BYID = 202;</code>
     *
     * <pre>
     * ID 登陆服务器
     * </pre>
     */
    public static final int GAMESERVER_LOGIN_BYID_VALUE = 202;
    /**
     * <code>GAMESERVER_LOGIN_BYPHONE = 203;</code>
     *
     * <pre>
     * 手机 登陆
     * </pre>
     */
    public static final int GAMESERVER_LOGIN_BYPHONE_VALUE = 203;
    /**
     * <code>GAMESERVER_SYS_TIME = 204;</code>
     *
     * <pre>
     * 时间同步
     * </pre>
     */
    public static final int GAMESERVER_SYS_TIME_VALUE = 204;
    /**
     * <code>SERVER_HEART = 3000;</code>
     *
     * <pre>
     * 心跳检测
     * </pre>
     */
    public static final int SERVER_HEART_VALUE = 3000;
    /**
     * <code>SERVER_REG = 2000;</code>
     *
     * <pre>
     * 注册协调服务器命令
     * </pre>
     */
    public static final int SERVER_REG_VALUE = 2000;
    /**
     * <code>GAME_ROOMINFO = 500;</code>
     *
     * <pre>
     * 游戏 房间信息
     * </pre>
     */
    public static final int GAME_ROOMINFO_VALUE = 500;
    /**
     * <code>GAME_USERINFO = 501;</code>
     *
     * <pre>
     * 用户信息
     * </pre>
     */
    public static final int GAME_USERINFO_VALUE = 501;
    /**
     * <code>GAME_TABLEINFO = 502;</code>
     *
     * <pre>
     * 桌子状态信息
     * </pre>
     */
    public static final int GAME_TABLEINFO_VALUE = 502;
    /**
     * <code>GAME_MATCHINFO = 503;</code>
     *
     * <pre>
     * 最新赛事
     * </pre>
     */
    public static final int GAME_MATCHINFO_VALUE = 503;
    /**
     * <code>GAMESERVER_MACHINFO = 7000;</code>
     *
     * <pre>
     * 请求比赛信息
     * </pre>
     */
    public static final int GAMESERVER_MACHINFO_VALUE = 7000;
    /**
     * <code>GAMESERVER_MACHSIGUP = 7001;</code>
     *
     * <pre>
     * 比赛报名
     * </pre>
     */
    public static final int GAMESERVER_MACHSIGUP_VALUE = 7001;
    /**
     * <code>GAMESERVER_WITHDRAW = 7002;</code>
     *
     * <pre>
     * 退出比赛
     * </pre>
     */
    public static final int GAMESERVER_WITHDRAW_VALUE = 7002;
    /**
     * <code>GAMESERVER_ENTERROOM = 8000;</code>
     *
     * <pre>
     * 用户进入房间
     * </pre>
     */
    public static final int GAMESERVER_ENTERROOM_VALUE = 8000;
    /**
     * <code>GAMESERVER_ENTERROOMTABLESTATE = 8001;</code>
     *
     * <pre>
     * 向玩家推送的桌子状态
     * </pre>
     */
    public static final int GAMESERVER_ENTERROOMTABLESTATE_VALUE = 8001;
    /**
     * <code>GAMESERVER_OTHERENTERROOM = 8002;</code>
     *
     * <pre>
     * 其他玩家进入房间
     * </pre>
     */
    public static final int GAMESERVER_OTHERENTERROOM_VALUE = 8002;
    /**
     * <code>GAMESERVER_CHAIRREQ = 8003;</code>
     *
     * <pre>
     * 请求椅子用户信息
     * </pre>
     */
    public static final int GAMESERVER_CHAIRREQ_VALUE = 8003;
    /**
     * <code>GAMESERVER_STANDUP = 8004;</code>
     *
     * <pre>
     * 用户站起
     * </pre>
     */
    public static final int GAMESERVER_STANDUP_VALUE = 8004;
    /**
     * <code>GAMESERVER_OTHERSTANDUP = 8005;</code>
     *
     * <pre>
     * 当前桌子玩家得到 得到退出用户信息
     * </pre>
     */
    public static final int GAMESERVER_OTHERSTANDUP_VALUE = 8005;
    /**
     * <code>GAMESERVER_LIVEROMM = 8007;</code>
     *
     * <pre>
     *用户离开房间
     * </pre>
     */
    public static final int GAMESERVER_LIVEROMM_VALUE = 8007;
    /**
     * <code>GAMESERVER_ENTERROOM_BYMOBILE = 8008;</code>
     *
     * <pre>
     *手机用户坐下操作
     * </pre>
     */
    public static final int GAMESERVER_ENTERROOM_BYMOBILE_VALUE = 8008;
    /**
     * <code>GAMESERVER_BANK_QUERY = 8009;</code>
     *
     * <pre>
     * 银行信息查询命令
     * </pre>
     */
    public static final int GAMESERVER_BANK_QUERY_VALUE = 8009;
    /**
     * <code>GAMESERVER_BANK_TAKE = 8010;</code>
     *
     * <pre>
     *提取游戏币
     * </pre>
     */
    public static final int GAMESERVER_BANK_TAKE_VALUE = 8010;
    /**
     * <code>GAMESERVER_QUER_FISHSCORE = 8011;</code>
     *
     * <pre>
     * 查询用户鱼粉
     * </pre>
     */
    public static final int GAMESERVER_QUER_FISHSCORE_VALUE = 8011;
    /**
     * <code>GAMESERVER_PUSHFISH = 8500;</code>
     *
     * <pre>
     * 推送普通鱼的命令
     * </pre>
     */
    public static final int GAMESERVER_PUSHFISH_VALUE = 8500;
    /**
     * <code>GAMESERVER_FISHFIRE = 8501;</code>
     *
     * <pre>
     * 开火命令
     * </pre>
     */
    public static final int GAMESERVER_FISHFIRE_VALUE = 8501;
    /**
     * <code>GAMESERVER_FISHFIREOTHER = 8502;</code>
     *
     * <pre>
     * 想其他玩家推送你的子弹消息
     * </pre>
     */
    public static final int GAMESERVER_FISHFIREOTHER_VALUE = 8502;
    /**
     * <code>GAMESERVER_FISHLOCKFISH = 8503;</code>
     *
     * <pre>
     * 锁定鱼的命令
     * </pre>
     */
    public static final int GAMESERVER_FISHLOCKFISH_VALUE = 8503;
    /**
     * <code>GAMESERVER_FISHLOCKFISHOTHER = 8504;</code>
     *
     * <pre>
     * 向其他玩家推送 你的锁定鱼的
     * </pre>
     */
    public static final int GAMESERVER_FISHLOCKFISHOTHER_VALUE = 8504;
    /**
     * <code>GAMESERVER_FISHCATCHFISH = 8505;</code>
     *
     * <pre>
     * 发送抓鱼命令
     * </pre>
     */
    public static final int GAMESERVER_FISHCATCHFISH_VALUE = 8505;
    /**
     * <code>GAMESERVER_FISHCATCHFISHOTHER = 8506;</code>
     *
     * <pre>
     * 向其他玩家推送你碰到鱼的命令
     * </pre>
     */
    public static final int GAMESERVER_FISHCATCHFISHOTHER_VALUE = 8506;
    /**
     * <code>GAMESERVER_FISHCHANGECANNON = 8508;</code>
     *
     * <pre>
     * 变炮
     * </pre>
     */
    public static final int GAMESERVER_FISHCHANGECANNON_VALUE = 8508;
    /**
     * <code>GAMESERVER_FISHCHANGECANNONOTHER = 8509;</code>
     *
     * <pre>
     * 想其他玩家推送你的变炮消息
     * </pre>
     */
    public static final int GAMESERVER_FISHCHANGECANNONOTHER_VALUE = 8509;
    /**
     * <code>GAMESERVER_PUSHFISHONEARRAY = 8510;</code>
     *
     * <pre>
     * 推送1号鱼阵信息
     * </pre>
     */
    public static final int GAMESERVER_PUSHFISHONEARRAY_VALUE = 8510;
    /**
     * <code>GAMESERVER_PUSHCHANGESCENE = 8511;</code>
     *
     * <pre>
     * 推送  场景切换
     * </pre>
     */
    public static final int GAMESERVER_PUSHCHANGESCENE_VALUE = 8511;
    /**
     * <code>GAMESERVER_PLAYERCOUNT = 8513;</code>
     *
     * <pre>
     *游戏服务器向协调推送最新在线玩家人数
     * </pre>
     */
    public static final int GAMESERVER_PLAYERCOUNT_VALUE = 8513;
    /**
     * <code>GAMESERVER_FISHCATCHSPEFISH = 8514;</code>
     *
     * <pre>
     * 发送特殊抓鱼命令
     * </pre>
     */
    public static final int GAMESERVER_FISHCATCHSPEFISH_VALUE = 8514;
    /**
     * <code>GAMESERVER_FISHCATCHFISHSPEOTHER = 8515;</code>
     *
     * <pre>
     * 向其他玩家推送你碰到鱼的命令
     * </pre>
     */
    public static final int GAMESERVER_FISHCATCHFISHSPEOTHER_VALUE = 8515;
    /**
     * <code>GAMESERVER_ENERGYCANNO = 8516;</code>
     *
     * <pre>
     * 能量炮
     * </pre>
     */
    public static final int GAMESERVER_ENERGYCANNO_VALUE = 8516;
    /**
     * <code>GAMESERVER_MATCHRESULT = 8520;</code>
     *
     * <pre>
     * 比赛结果信息
     * </pre>
     */
    public static final int GAMESERVER_MATCHRESULT_VALUE = 8520;
    /**
     * <code>GAMESERVER_MATCHRANKRESULT = 8521;</code>
     *
     * <pre>
     * 比赛名次信息
     * </pre>
     */
    public static final int GAMESERVER_MATCHRANKRESULT_VALUE = 8521;
    /**
     * <code>GAMESERVER_ONLINE_REWARD = 8522;</code>
     *
     * <pre>
     * 当前玩家领取奖励情况
     * </pre>
     */
    public static final int GAMESERVER_ONLINE_REWARD_VALUE = 8522;
    /**
     * <code>GAMESERVER_ONLINE_RECEIVE_REWARD = 8523;</code>
     *
     * <pre>
     * 用户点击领取奖励
     * </pre>
     */
    public static final int GAMESERVER_ONLINE_RECEIVE_REWARD_VALUE = 8523;
    /**
     * <code>GAMESERVER_TASK = 8524;</code>
     *
     * <pre>
     * 用户获取任务接口
     * </pre>
     */
    public static final int GAMESERVER_TASK_VALUE = 8524;
    /**
     * <code>GAMESERVER_REFE_TASK = 8525;</code>
     *
     * <pre>
     *用户刷新任务接口
     * </pre>
     */
    public static final int GAMESERVER_REFE_TASK_VALUE = 8525;
    /**
     * <code>GAMESERVER_TAKE_TASK = 8526;</code>
     *
     * <pre>
     *用户领取任务
     * </pre>
     */
    public static final int GAMESERVER_TAKE_TASK_VALUE = 8526;
    /**
     * <code>GAMESERVER_TAKE_TASK_REWARD = 8527;</code>
     *
     * <pre>
     * 用户领取任务奖励
     * </pre>
     */
    public static final int GAMESERVER_TAKE_TASK_REWARD_VALUE = 8527;
    /**
     * <code>GAMESERVER_TASK_COUNT_REF = 8528;</code>
     *
     * <pre>
     * 用户任务完成度刷新
     * </pre>
     */
    public static final int GAMESERVER_TASK_COUNT_REF_VALUE = 8528;
    /**
     * <code>GAMESERVER_TOTAL_TASK_REF = 8529;</code>
     *
     * <pre>
     * 零点任务已完成总数量刷新
     * </pre>
     */
    public static final int GAMESERVER_TOTAL_TASK_REF_VALUE = 8529;
    /**
     * <code>GAMESERVER_PROPDROP = 8530;</code>
     *
     * <pre>
     * 获取道具
     * </pre>
     */
    public static final int GAMESERVER_PROPDROP_VALUE = 8530;
    /**
     * <code>GAMESERVER_ARENAPRIZE = 8531;</code>
     *
     * <pre>
     * 获取积分奖励列表
     * </pre>
     */
    public static final int GAMESERVER_ARENAPRIZE_VALUE = 8531;
    /**
     * <code>GAMESERVER_ARENATAKE_PRIZE = 8532;</code>
     *
     * <pre>
     *领取积分奖励
     * </pre>
     */
    public static final int GAMESERVER_ARENATAKE_PRIZE_VALUE = 8532;
    /**
     * <code>GAMESERVER_FISH_TIPS = 8533;</code>
     *
     * <pre>
     *鱼的提示语
     * </pre>
     */
    public static final int GAMESERVER_FISH_TIPS_VALUE = 8533;
    /**
     * <code>COORDINATIONSERVER_ROOMINFO = 4000;</code>
     *
     * <pre>
     *协调服务器命令
     * </pre>
     */
    public static final int COORDINATIONSERVER_ROOMINFO_VALUE = 4000;
    /**
     * <code>COORDINATIONSERVER_ROOMCOUNT = 4001;</code>
     *
     * <pre>
     * 协调推送过来的 房间人数信息
     * </pre>
     */
    public static final int COORDINATIONSERVER_ROOMCOUNT_VALUE = 4001;
    /**
     * <code>COORDINATIONSERVER_REMOVE_ROOMINFO = 4002;</code>
     *
     * <pre>
     * 协调推送的删除房间信息
     * </pre>
     */
    public static final int COORDINATIONSERVER_REMOVE_ROOMINFO_VALUE = 4002;
    /**
     * <code>COORDINATIONSERVER_SERVER_MESSAGE = 4003;</code>
     *
     * <pre>
     *  其他服务器给协调放聊天信息或者系统消息
     * </pre>
     */
    public static final int COORDINATIONSERVER_SERVER_MESSAGE_VALUE = 4003;
    /**
     * <code>COORDINATIONSERVER_ROOMLIST = 4004;</code>
     *
     * <pre>
     * 想协调服务器请求当前所有的服务
     * </pre>
     */
    public static final int COORDINATIONSERVER_ROOMLIST_VALUE = 4004;
    /**
     * <code>COORDINATIONSERVER_PLAYERCOUNT = 4005;</code>
     *
     * <pre>
     * 请求连接协调的游戏服务器上的在线人数
     * </pre>
     */
    public static final int COORDINATIONSERVER_PLAYERCOUNT_VALUE = 4005;
    /**
     * <code>COORDINATIONSERVER_STOP = 4006;</code>
     *
     * <pre>
     * 鍋滄湇鍛戒护
     * </pre>
     */
    public static final int COORDINATIONSERVER_STOP_VALUE = 4006;
    /**
     * <code>COORDINATIONSERVER_SEARCHROOMSTOCK = 4007;</code>
     *
     * <pre>
     *查询房间的库存
     * </pre>
     */
    public static final int COORDINATIONSERVER_SEARCHROOMSTOCK_VALUE = 4007;
    /**
     * <code>COORDINATIONSERVER_SEARCHROOMSTOCKRESP = 4008;</code>
     *
     * <pre>
     *查询房间库存的值
     * </pre>
     */
    public static final int COORDINATIONSERVER_SEARCHROOMSTOCKRESP_VALUE = 4008;
    /**
     * <code>COORDINATIONSERVER_UPDATEROOMSTOCK = 4009;</code>
     *
     * <pre>
     *修改库存值
     * </pre>
     */
    public static final int COORDINATIONSERVER_UPDATEROOMSTOCK_VALUE = 4009;
    /**
     * <code>COORDINATIONSERVER_UPDATEROOMSTOCKRESP = 4010;</code>
     *
     * <pre>
     *修改库存成功
     * </pre>
     */
    public static final int COORDINATIONSERVER_UPDATEROOMSTOCKRESP_VALUE = 4010;
    /**
     * <code>COORDINATIONSERVER_KICKOUTUSER = 4011;</code>
     *
     * <pre>
     * 强制踢出在线玩家
     * </pre>
     */
    public static final int COORDINATIONSERVER_KICKOUTUSER_VALUE = 4011;
    /**
     * <code>COORDINATIONSERVER_SYNCPROFILE = 4012;</code>
     *
     * <pre>
     * 同步配置文件
     * </pre>
     */
    public static final int COORDINATIONSERVER_SYNCPROFILE_VALUE = 4012;
    /**
     * <code>COORDINATIONSERVER_KICKLOGINUSER = 4013;</code>
     *
     * <pre>
     * 踢出别的服务器上的当前玩家
     * </pre>
     */
    public static final int COORDINATIONSERVER_KICKLOGINUSER_VALUE = 4013;
    /**
     * <code>COORDINATIONSERVER_SYNCCONF = 4014;</code>
     *
     * <pre>
     * 同步配置文件 4012
     * </pre>
     */
    public static final int COORDINATIONSERVER_SYNCCONF_VALUE = 4014;
    /**
     * <code>LOGIN_FETCH_VERIFY_CODE = 825;</code>
     *
     * <pre>
     *获取验证码
     * </pre>
     */
    public static final int LOGIN_FETCH_VERIFY_CODE_VALUE = 825;
    /**
     * <code>LOGIN_ACCOUNTS_BIND = 826;</code>
     *
     * <pre>
     *绑定账号
     * </pre>
     */
    public static final int LOGIN_ACCOUNTS_BIND_VALUE = 826;
    /**
     * <code>LOGIN_ACCOUNTS_DEBIND = 827;</code>
     *
     * <pre>
     *解绑账号
     * </pre>
     */
    public static final int LOGIN_ACCOUNTS_DEBIND_VALUE = 827;
    /**
     * <code>LOGIN_FETCH_PLAYER_INFO = 828;</code>
     *
     * <pre>
     *获取玩家信息
     * </pre>
     */
    public static final int LOGIN_FETCH_PLAYER_INFO_VALUE = 828;
    /**
     * <code>LOGIN_PACK_ITEM_OPT = 830;</code>
     *
     * <pre>
     *背包操作
     * </pre>
     */
    public static final int LOGIN_PACK_ITEM_OPT_VALUE = 830;
    /**
     * <code>LOGIN_PACK_ITEM_RELOAD = 831;</code>
     *
     * <pre>
     *重新拉取背包操作
     * </pre>
     */
    public static final int LOGIN_PACK_ITEM_RELOAD_VALUE = 831;
    /**
     * <code>LOGIN_FESTIVAL_PRIZE_CHECK = 832;</code>
     *
     * <pre>
     *检查是可以领取节日奖励
     * </pre>
     */
    public static final int LOGIN_FESTIVAL_PRIZE_CHECK_VALUE = 832;
    /**
     * <code>LOGIN_FESTIVAL_PRIZE_GET = 833;</code>
     *
     * <pre>
     *领取节日奖励
     * </pre>
     */
    public static final int LOGIN_FESTIVAL_PRIZE_GET_VALUE = 833;
    /**
     * <code>LOGIN_FETCH_UPLOAD_TOKEN = 834;</code>
     *
     * <pre>
     *获取上传token
     * </pre>
     */
    public static final int LOGIN_FETCH_UPLOAD_TOKEN_VALUE = 834;
    /**
     * <code>GAME_MATCH_QUERY_START_TIME = 840;</code>
     *
     * <pre>
     *获取比赛开始时间
     * </pre>
     */
    public static final int GAME_MATCH_QUERY_START_TIME_VALUE = 840;
    /**
     * <code>GAME_SERVER_MATCH_WIN_SCORE = 841;</code>
     *
     * <pre>
     *广播名次和分数
     * </pre>
     */
    public static final int GAME_SERVER_MATCH_WIN_SCORE_VALUE = 841;
    /**
     * <code>GAME_SERVER_MATCH_OVER_SCORE = 842;</code>
     *
     * <pre>
     *游戏结束时广播成绩
     * </pre>
     */
    public static final int GAME_SERVER_MATCH_OVER_SCORE_VALUE = 842;
    /**
     * <code>GAME_SERVER_REGISTER_TO_MATCH_CMD = 843;</code>
     *
     * <pre>
     *注册游戏服到MatchServer
     * </pre>
     */
    public static final int GAME_SERVER_REGISTER_TO_MATCH_CMD_VALUE = 843;
    /**
     * <code>GAME_SERVER_MATCH_SIT_DOWN = 844;</code>
     *
     * <pre>
     *比赛玩家坐下
     * </pre>
     */
    public static final int GAME_SERVER_MATCH_SIT_DOWN_VALUE = 844;
    /**
     * <code>LOGIN_SERVER_HD_GET_INFO = 845;</code>
     *
     * <pre>
     *获取活动信息
     * </pre>
     */
    public static final int LOGIN_SERVER_HD_GET_INFO_VALUE = 845;
    /**
     * <code>LOGIN_SERVER_HD_OPEN = 846;</code>
     *
     * <pre>
     *开活动物品
     * </pre>
     */
    public static final int LOGIN_SERVER_HD_OPEN_VALUE = 846;
    /**
     * <code>LOGIN_SERVER_RAND_INFO = 847;</code>
     *
     * <pre>
     *获取活动排行
     * </pre>
     */
    public static final int LOGIN_SERVER_RAND_INFO_VALUE = 847;
    /**
     * <code>LOGIN_SERVER_RED_POINT = 848;</code>
     *
     * <pre>
     *推送红点信息
     * </pre>
     */
    public static final int LOGIN_SERVER_RED_POINT_VALUE = 848;
    /**
     * <code>LOGIN_SERVER_CLIENT_NEED = 849;</code>
     *
     * <pre>
     *推送客户端需要配置信息
     * </pre>
     */
    public static final int LOGIN_SERVER_CLIENT_NEED_VALUE = 849;
    /**
     * <code>LOGIN_SERVER_ACTIVITY_QUERY = 850;</code>
     *
     * <pre>
     *查询vip可兑换的豆
     * </pre>
     */
    public static final int LOGIN_SERVER_ACTIVITY_QUERY_VALUE = 850;
    /**
     * <code>LOGIN_SERVER_ACTIVITY_EXECUTE = 851;</code>
     *
     * <pre>
     *领取vip奖励
     * </pre>
     */
    public static final int LOGIN_SERVER_ACTIVITY_EXECUTE_VALUE = 851;
    /**
     * <code>LOGIN_SERVER_ACTIVITY_LIST = 852;</code>
     */
    public static final int LOGIN_SERVER_ACTIVITY_LIST_VALUE = 852;
    /**
     * <code>LOGIN_SERVER_CHARGE_TOOL_AWARD = 853;</code>
     */
    public static final int LOGIN_SERVER_CHARGE_TOOL_AWARD_VALUE = 853;
    /**
     * <code>LOGIN_SERVER_MAIL_LIST = 860;</code>
     *
     * <pre>
     *请求邮件列表
     * </pre>
     */
    public static final int LOGIN_SERVER_MAIL_LIST_VALUE = 860;
    /**
     * <code>LOGIN_SERVER_MAILS = 861;</code>
     *
     * <pre>
     *请求邮件内容
     * </pre>
     */
    public static final int LOGIN_SERVER_MAILS_VALUE = 861;
    /**
     * <code>LOGIN_SERVER_OPT_MAIL = 862;</code>
     *
     * <pre>
     *对邮件进行操作
     * </pre>
     */
    public static final int LOGIN_SERVER_OPT_MAIL_VALUE = 862;
    /**
     * <code>LOGIN_SERVER_ADVISE_CLIENT_MAIL = 863;</code>
     *
     * <pre>
     *通知客户端拉取邮件
     * </pre>
     */
    public static final int LOGIN_SERVER_ADVISE_CLIENT_MAIL_VALUE = 863;
    /**
     * <code>LOGIN_SERVER_VIP_SHOW = 864;</code>
     *
     * <pre>
     *vip展示
     * </pre>
     */
    public static final int LOGIN_SERVER_VIP_SHOW_VALUE = 864;
    /**
     * <code>LOGIN_SERVER_VIP_CHARGE = 865;</code>
     *
     * <pre>
     *获取vip充值
     * </pre>
     */
    public static final int LOGIN_SERVER_VIP_CHARGE_VALUE = 865;
    /**
     * <code>LOGIN_SERVER_GET_CHARGE_LIST = 866;</code>
     *
     * <pre>
     *获取充值列表
     * </pre>
     */
    public static final int LOGIN_SERVER_GET_CHARGE_LIST_VALUE = 866;
    /**
     * <code>LOGIN_SERVER_MATCH_TZ_BAOMING = 867;</code>
     *
     * <pre>
     *挑战赛报名
     * </pre>
     */
    public static final int LOGIN_SERVER_MATCH_TZ_BAOMING_VALUE = 867;
    /**
     * <code>LOGIN_SERVER_TASK_QUERY = 870;</code>
     *
     * <pre>
     *查询任务进度
     * </pre>
     */
    public static final int LOGIN_SERVER_TASK_QUERY_VALUE = 870;
    /**
     * <code>LOGIN_SERVER_TASK_RECV = 871;</code>
     *
     * <pre>
     *领取任务奖励
     * </pre>
     */
    public static final int LOGIN_SERVER_TASK_RECV_VALUE = 871;
    /**
     * <code>LOGIN_SERVER_LGDB_QUERY = 8601;</code>
     *
     * <pre>
     *龙宫夺宝加载信息CMD
     * </pre>
     */
    public static final int LOGIN_SERVER_LGDB_QUERY_VALUE = 8601;
    /**
     * <code>LOGIN_SERVER_LGDB_RESET = 8602;</code>
     *
     * <pre>
     *龙宫夺宝刷新转盘
     * </pre>
     */
    public static final int LOGIN_SERVER_LGDB_RESET_VALUE = 8602;
    /**
     * <code>LOGIN_SERVER_LGDB_RUN = 8603;</code>
     *
     * <pre>
     *龙宫夺宝抽奖
     * </pre>
     */
    public static final int LOGIN_SERVER_LGDB_RUN_VALUE = 8603;
    /**
     * <code>LOGIN_SERVER_LGDB_RECV = 8604;</code>
     *
     * <pre>
     *龙宫夺宝领排行榜奖励
     * </pre>
     */
    public static final int LOGIN_SERVER_LGDB_RECV_VALUE = 8604;
    /**
     * <code>LOGIN_SERVER_LGDB_HISTORY = 8605;</code>
     *
     * <pre>
     *龙宫夺宝抽奖历史记录
     * </pre>
     */
    public static final int LOGIN_SERVER_LGDB_HISTORY_VALUE = 8605;
    /**
     * <code>LOGIN_SERVER_LGDB_RANK = 8606;</code>
     *
     * <pre>
     *查询龙宫夺宝排行榜信息
     * </pre>
     */
    public static final int LOGIN_SERVER_LGDB_RANK_VALUE = 8606;
    /**
     * <code>LOGIN_SERVER_LGDB_PUSH_SUPER_AWARD = 8607;</code>
     *
     * <pre>
     *有人拿到大奖后,推送到客户端
     * </pre>
     */
    public static final int LOGIN_SERVER_LGDB_PUSH_SUPER_AWARD_VALUE = 8607;
    /**
     * <code>GAME_SERVER_RECONNECT_SEND_INFO = 8608;</code>
     *
     * <pre>
     *客户端重连到新的loginserver之后,发送其最新位置给游戏服务器
     * </pre>
     */
    public static final int GAME_SERVER_RECONNECT_SEND_INFO_VALUE = 8608;
    /**
     * <code>GAME_SERVER_TZ_STAGE_INFO = 8700;</code>
     *
     * <pre>
     *挑战赛阶段信息
     * </pre>
     */
    public static final int GAME_SERVER_TZ_STAGE_INFO_VALUE = 8700;
    /**
     * <code>GAME_SERVER_TZ_SCORE_ENOUGH = 8701;</code>
     *
     * <pre>
     *挑战赛分数已足
     * </pre>
     */
    public static final int GAME_SERVER_TZ_SCORE_ENOUGH_VALUE = 8701;
    /**
     * <code>GAME_SERVER_TZ_OVER_OPT = 8702;</code>
     *
     * <pre>
     *挑战赛分数已足
     * </pre>
     */
    public static final int GAME_SERVER_TZ_OVER_OPT_VALUE = 8702;
    /**
     * <code>GAME_SERVER_GIVEUP = 8703;</code>
     *
     * <pre>
     * 放弃比赛
     * </pre>
     */
    public static final int GAME_SERVER_GIVEUP_VALUE = 8703;
    /**
     * <code>LOGIN_SERVER_MAILS_OVER = 8610;</code>
     *
     * <pre>
     *邮件发送结束
     * </pre>
     */
    public static final int LOGIN_SERVER_MAILS_OVER_VALUE = 8610;
    /**
     * <code>LOGIN_SERVER_SEND_LUA_VERSION = 900;</code>
     *
     * <pre>
     *发送lua版本
     * </pre>
     */
    public static final int LOGIN_SERVER_SEND_LUA_VERSION_VALUE = 900;
    /**
     * <code>LOGIN_PACK_QUERY_COMPOSE = 920;</code>
     */
    public static final int LOGIN_PACK_QUERY_COMPOSE_VALUE = 920;
    /**
     * <code>LOGIN_PACK_DO_COMPOSE = 921;</code>
     */
    public static final int LOGIN_PACK_DO_COMPOSE_VALUE = 921;
    /**
     * <code>LOGIN_SERVER_ARENA_DAY_RANK = 922;</code>
     */
    public static final int LOGIN_SERVER_ARENA_DAY_RANK_VALUE = 922;
    /**
     * <code>LOGIN_SERVER_ARENA_WEEK_RANK = 923;</code>
     */
    public static final int LOGIN_SERVER_ARENA_WEEK_RANK_VALUE = 923;
    /**
     * <code>LOGIN_SERVER_ARENA_README = 924;</code>
     */
    public static final int LOGIN_SERVER_ARENA_README_VALUE = 924;
    /**
     * <code>LOGIN_ARENA_UNLOCK = 1000;</code>
     *
     * <pre>
     *解锁竞技场
     * </pre>
     */
    public static final int LOGIN_ARENA_UNLOCK_VALUE = 1000;
    /**
     * <code>LOGIN_ARENA_QUERY_BOARD = 1001;</code>
     *
     * <pre>
     *请求竞技场board
     * </pre>
     */
    public static final int LOGIN_ARENA_QUERY_BOARD_VALUE = 1001;
    /**
     * <code>LOGIN_ARENA_SIGN = 1002;</code>
     *
     * <pre>
     *竞技场报名
     * </pre>
     */
    public static final int LOGIN_ARENA_SIGN_VALUE = 1002;
    /**
     * <code>LOGIN_ARENA_REPORT = 1003;</code>
     *
     * <pre>
     *竞技场奖状
     * </pre>
     */
    public static final int LOGIN_ARENA_REPORT_VALUE = 1003;
    /**
     * <code>LOGIN_ARENA_FUNC_STATUS = 1004;</code>
     */
    public static final int LOGIN_ARENA_FUNC_STATUS_VALUE = 1004;
    /**
     * <code>LOGIN_ARENA_UNLOCK_CHECK = 1005;</code>
     */
    public static final int LOGIN_ARENA_UNLOCK_CHECK_VALUE = 1005;
    /**
     * <code>LOGIN_ARENA_QUERY_UPPER_BOARD = 1009;</code>
     */
    public static final int LOGIN_ARENA_QUERY_UPPER_BOARD_VALUE = 1009;
    /**
     * <code>LOGIN_FREE_GOLD_FETCH_INFO = 1006;</code>
     */
    public static final int LOGIN_FREE_GOLD_FETCH_INFO_VALUE = 1006;
    /**
     * <code>LOGIN_FREE_GOLD_INCOME_LIST = 1007;</code>
     */
    public static final int LOGIN_FREE_GOLD_INCOME_LIST_VALUE = 1007;
    /**
     * <code>LOGIN_FREE_GOLD_EXCHANGE = 1008;</code>
     */
    public static final int LOGIN_FREE_GOLD_EXCHANGE_VALUE = 1008;
    /**
     * <code>LOGIN_FREE_GOLD_README = 1010;</code>
     */
    public static final int LOGIN_FREE_GOLD_README_VALUE = 1010;
    /**
     * <code>REFRESH = 10000;</code>
     */
    public static final int REFRESH_VALUE = 10000;
    /**
     * <code>CREATE_ORDER = 600;</code>
     *
     * <pre>
     *创建订单
     * </pre>
     */
    public static final int CREATE_ORDER_VALUE = 600;
    /**
     * <code>QUERY_ORDER = 601;</code>
     *
     * <pre>
     *查询订单
     * </pre>
     */
    public static final int QUERY_ORDER_VALUE = 601;
    /**
     * <code>PUT_CLIENT_IP = 999;</code>
     *
     * <pre>
     *推送客户端IP
     * </pre>
     */
    public static final int PUT_CLIENT_IP_VALUE = 999;


    public final int getNumber() { return value; }

    public static CmdCode valueOf(int value) {
      switch (value) {
        case 5000: return SERVER_ERROR;
        case 99: return LOGINSERVER_LOGIN_BYPHONE;
        case 100: return LOGINSERVER_LOGIN;
        case 101: return LOGINSERVER_REGIST;
        case 300: return GAMEROOM_LIST;
        case 301: return GAMETYPE_LIST;
        case 302: return GAMEINFOOFGAMETYPE;
        case 303: return GAMEROOMTYPE_LIST;
        case 304: return GAMEROOMTYPE;
        case 305: return USERLOCKMACHINE;
        case 306: return LOGINSERVER_SYSMESG;
        case 307: return LOGINSERVER_PUBLIC_SYSMESG;
        case 400: return BANK_RECORD_QUERY;
        case 401: return BANK_QUERY;
        case 402: return BANK_SAVE;
        case 403: return BANK_TAKE;
        case 404: return BANK_TRANSFER;
        case 405: return BANK_EXCHANGE;
        case 406: return BANK_PROP_TO_SCORE;
        case 407: return TAKE_GOLD;
        case 408: return TIME_SYN;
        case 409: return GET_GOODS_VALUE;
        case 410: return GIVE_ROSE;
        case 411: return GIVE_ROSE_OTHER;
        case 412: return GAMEPAYOK;
        case 413: return USERCONTROL;
        case 414: return USERINVITEDSCORECMD;
        case 415: return INVITEUSERSCORECMD;
        case 416: return USER_SEND_RADPACKET;
        case 417: return USER_GET_RADPACKET;
        case 418: return INVITEUSERCOUNTCMD;
        case 419: return INVITEORSHARECOUNT;
        case 420: return INVITEORSHARE;
        case 421: return TRANS_STR_IN;
        case 422: return SHARE_QUERY;
        case 423: return SHARE_SUCCESS_NOTICE;
        case 424: return SHARE_OPEN_BOX;
        case 425: return SHARE_QUERY_DETAIL;
        case 430: return PRESENT_QUERY;
        case 431: return PRESENT_GOLD;
        case 433: return BULLSCORE_USE_LIST;
        case 434: return BULLSCORE_USE;
        case 435: return BULLSCORE_USE_HISTORY;
        case 440: return PAY_IOS_RECEIPRT;
        case 441: return PAY_INDEX;
        case 800: return USERINFO_GETCOMMONINFO;
        case 801: return USERINFO_GETDETAILINFO;
        case 802: return USERINFO_UPDATE_LOGINPWD;
        case 803: return USERINFO_UPDATE_INSUREPWD;
        case 804: return USERINFO_UPDATE_COMMONINFO;
        case 805: return USERINFO_UPDATE_DETAILINFO;
        case 806: return USERINFO_QMFD_JOINGAME;
        case 807: return USERINFO_QMFD_RANKING;
        case 808: return USERINFO_QMFD_SETTLEMENT;
        case 809: return USERINFO_QMFD_STARTUP;
        case 810: return USERINFO_ZZ_GET;
        case 811: return USERINFO_ZZ_RANK;
        case 812: return USERINFO_ZZ_OPEN;
        case 813: return USERINFO_ZZ_BUY;
        case 814: return USERINFO_RANK_SHOW;
        case 815: return USERINFO_RANK_THUMB_UP;
        case 816: return USERINFO_RANK_RECV_AWARD;
        case 819: return LOGINSERVER_QIANDAO_INDEX;
        case 820: return LOGINSERVER_QIANDAO;
        case 821: return LOGINSERVER_QIANDAO_RECV_TOTAL;
        case 822: return LOGINSERVER_QIANDAO_CHANGE_TIME;
        case 8301: return LOGINSERVER_MATCH_FETCH_ACT_LIST;
        case 8302: return LOGINSERVER_MATCH_BAO_MING;
        case 8303: return LOGINSERVER_MATCH_CANCEL;
        case 8304: return LOGINSERVER_MATCH_FETCH_TYPES;
        case 8305: return LOGINSERVER_MATCH_FETCH_TYPE_DETAIL;
        case 8306: return LOGINSERVER_MATCH_REFRESH_PERSON_COUNT;
        case 8307: return LOGINSERVER_MATCH_BEGIN;
        case 8308: return LOGINSERVER_MATCH_GIVEUP;
        case 8309: return LOGINSERVER_MATCH_BEGIN_PULL;
        case 8310: return LOGIN_SERVER_CHAT_SEND;
        case 8311: return LOGIN_SERVER_CHAT_RECEIVE;
        case 8312: return GAME_SERVER_CHAT_SEND;
        case 8313: return GAME_SERVER_CHAT_RECEIVE;
        case 8314: return GAME_SERVER_REFRESH_USER_STATUS;
        case 8315: return GAME_SERVER_UPDATE_NOTICE_LIST;
        case 8316: return LOGIN_SERVER_CHAT_DLG_OPERATION;
        case 8317: return SERVER_REFRESH_SERVER_STATUS;
        case 8318: return LOGIN_SERVER_SUPER_CHARGE;
        case 8319: return LOGIN_SERVER_MATCH_OL_COUNT;
        case 8320: return LOGIN_GET_SCORE;
        case 8321: return GET_FREE_SCORE;
        case 200: return GAMESERVER_LOGIN;
        case 201: return GAMESERVER_OTHERLOGIN;
        case 202: return GAMESERVER_LOGIN_BYID;
        case 203: return GAMESERVER_LOGIN_BYPHONE;
        case 204: return GAMESERVER_SYS_TIME;
        case 3000: return SERVER_HEART;
        case 2000: return SERVER_REG;
        case 500: return GAME_ROOMINFO;
        case 501: return GAME_USERINFO;
        case 502: return GAME_TABLEINFO;
        case 503: return GAME_MATCHINFO;
        case 7000: return GAMESERVER_MACHINFO;
        case 7001: return GAMESERVER_MACHSIGUP;
        case 7002: return GAMESERVER_WITHDRAW;
        case 8000: return GAMESERVER_ENTERROOM;
        case 8001: return GAMESERVER_ENTERROOMTABLESTATE;
        case 8002: return GAMESERVER_OTHERENTERROOM;
        case 8003: return GAMESERVER_CHAIRREQ;
        case 8004: return GAMESERVER_STANDUP;
        case 8005: return GAMESERVER_OTHERSTANDUP;
        case 8007: return GAMESERVER_LIVEROMM;
        case 8008: return GAMESERVER_ENTERROOM_BYMOBILE;
        case 8009: return GAMESERVER_BANK_QUERY;
        case 8010: return GAMESERVER_BANK_TAKE;
        case 8011: return GAMESERVER_QUER_FISHSCORE;
        case 8500: return GAMESERVER_PUSHFISH;
        case 8501: return GAMESERVER_FISHFIRE;
        case 8502: return GAMESERVER_FISHFIREOTHER;
        case 8503: return GAMESERVER_FISHLOCKFISH;
        case 8504: return GAMESERVER_FISHLOCKFISHOTHER;
        case 8505: return GAMESERVER_FISHCATCHFISH;
        case 8506: return GAMESERVER_FISHCATCHFISHOTHER;
        case 8508: return GAMESERVER_FISHCHANGECANNON;
        case 8509: return GAMESERVER_FISHCHANGECANNONOTHER;
        case 8510: return GAMESERVER_PUSHFISHONEARRAY;
        case 8511: return GAMESERVER_PUSHCHANGESCENE;
        case 8513: return GAMESERVER_PLAYERCOUNT;
        case 8514: return GAMESERVER_FISHCATCHSPEFISH;
        case 8515: return GAMESERVER_FISHCATCHFISHSPEOTHER;
        case 8516: return GAMESERVER_ENERGYCANNO;
        case 8520: return GAMESERVER_MATCHRESULT;
        case 8521: return GAMESERVER_MATCHRANKRESULT;
        case 8522: return GAMESERVER_ONLINE_REWARD;
        case 8523: return GAMESERVER_ONLINE_RECEIVE_REWARD;
        case 8524: return GAMESERVER_TASK;
        case 8525: return GAMESERVER_REFE_TASK;
        case 8526: return GAMESERVER_TAKE_TASK;
        case 8527: return GAMESERVER_TAKE_TASK_REWARD;
        case 8528: return GAMESERVER_TASK_COUNT_REF;
        case 8529: return GAMESERVER_TOTAL_TASK_REF;
        case 8530: return GAMESERVER_PROPDROP;
        case 8531: return GAMESERVER_ARENAPRIZE;
        case 8532: return GAMESERVER_ARENATAKE_PRIZE;
        case 8533: return GAMESERVER_FISH_TIPS;
        case 4000: return COORDINATIONSERVER_ROOMINFO;
        case 4001: return COORDINATIONSERVER_ROOMCOUNT;
        case 4002: return COORDINATIONSERVER_REMOVE_ROOMINFO;
        case 4003: return COORDINATIONSERVER_SERVER_MESSAGE;
        case 4004: return COORDINATIONSERVER_ROOMLIST;
        case 4005: return COORDINATIONSERVER_PLAYERCOUNT;
        case 4006: return COORDINATIONSERVER_STOP;
        case 4007: return COORDINATIONSERVER_SEARCHROOMSTOCK;
        case 4008: return COORDINATIONSERVER_SEARCHROOMSTOCKRESP;
        case 4009: return COORDINATIONSERVER_UPDATEROOMSTOCK;
        case 4010: return COORDINATIONSERVER_UPDATEROOMSTOCKRESP;
        case 4011: return COORDINATIONSERVER_KICKOUTUSER;
        case 4012: return COORDINATIONSERVER_SYNCPROFILE;
        case 4013: return COORDINATIONSERVER_KICKLOGINUSER;
        case 4014: return COORDINATIONSERVER_SYNCCONF;
        case 825: return LOGIN_FETCH_VERIFY_CODE;
        case 826: return LOGIN_ACCOUNTS_BIND;
        case 827: return LOGIN_ACCOUNTS_DEBIND;
        case 828: return LOGIN_FETCH_PLAYER_INFO;
        case 830: return LOGIN_PACK_ITEM_OPT;
        case 831: return LOGIN_PACK_ITEM_RELOAD;
        case 832: return LOGIN_FESTIVAL_PRIZE_CHECK;
        case 833: return LOGIN_FESTIVAL_PRIZE_GET;
        case 834: return LOGIN_FETCH_UPLOAD_TOKEN;
        case 840: return GAME_MATCH_QUERY_START_TIME;
        case 841: return GAME_SERVER_MATCH_WIN_SCORE;
        case 842: return GAME_SERVER_MATCH_OVER_SCORE;
        case 843: return GAME_SERVER_REGISTER_TO_MATCH_CMD;
        case 844: return GAME_SERVER_MATCH_SIT_DOWN;
        case 845: return LOGIN_SERVER_HD_GET_INFO;
        case 846: return LOGIN_SERVER_HD_OPEN;
        case 847: return LOGIN_SERVER_RAND_INFO;
        case 848: return LOGIN_SERVER_RED_POINT;
        case 849: return LOGIN_SERVER_CLIENT_NEED;
        case 850: return LOGIN_SERVER_ACTIVITY_QUERY;
        case 851: return LOGIN_SERVER_ACTIVITY_EXECUTE;
        case 852: return LOGIN_SERVER_ACTIVITY_LIST;
        case 853: return LOGIN_SERVER_CHARGE_TOOL_AWARD;
        case 860: return LOGIN_SERVER_MAIL_LIST;
        case 861: return LOGIN_SERVER_MAILS;
        case 862: return LOGIN_SERVER_OPT_MAIL;
        case 863: return LOGIN_SERVER_ADVISE_CLIENT_MAIL;
        case 864: return LOGIN_SERVER_VIP_SHOW;
        case 865: return LOGIN_SERVER_VIP_CHARGE;
        case 866: return LOGIN_SERVER_GET_CHARGE_LIST;
        case 867: return LOGIN_SERVER_MATCH_TZ_BAOMING;
        case 870: return LOGIN_SERVER_TASK_QUERY;
        case 871: return LOGIN_SERVER_TASK_RECV;
        case 8601: return LOGIN_SERVER_LGDB_QUERY;
        case 8602: return LOGIN_SERVER_LGDB_RESET;
        case 8603: return LOGIN_SERVER_LGDB_RUN;
        case 8604: return LOGIN_SERVER_LGDB_RECV;
        case 8605: return LOGIN_SERVER_LGDB_HISTORY;
        case 8606: return LOGIN_SERVER_LGDB_RANK;
        case 8607: return LOGIN_SERVER_LGDB_PUSH_SUPER_AWARD;
        case 8608: return GAME_SERVER_RECONNECT_SEND_INFO;
        case 8700: return GAME_SERVER_TZ_STAGE_INFO;
        case 8701: return GAME_SERVER_TZ_SCORE_ENOUGH;
        case 8702: return GAME_SERVER_TZ_OVER_OPT;
        case 8703: return GAME_SERVER_GIVEUP;
        case 8610: return LOGIN_SERVER_MAILS_OVER;
        case 900: return LOGIN_SERVER_SEND_LUA_VERSION;
        case 920: return LOGIN_PACK_QUERY_COMPOSE;
        case 921: return LOGIN_PACK_DO_COMPOSE;
        case 922: return LOGIN_SERVER_ARENA_DAY_RANK;
        case 923: return LOGIN_SERVER_ARENA_WEEK_RANK;
        case 924: return LOGIN_SERVER_ARENA_README;
        case 1000: return LOGIN_ARENA_UNLOCK;
        case 1001: return LOGIN_ARENA_QUERY_BOARD;
        case 1002: return LOGIN_ARENA_SIGN;
        case 1003: return LOGIN_ARENA_REPORT;
        case 1004: return LOGIN_ARENA_FUNC_STATUS;
        case 1005: return LOGIN_ARENA_UNLOCK_CHECK;
        case 1009: return LOGIN_ARENA_QUERY_UPPER_BOARD;
        case 1006: return LOGIN_FREE_GOLD_FETCH_INFO;
        case 1007: return LOGIN_FREE_GOLD_INCOME_LIST;
        case 1008: return LOGIN_FREE_GOLD_EXCHANGE;
        case 1010: return LOGIN_FREE_GOLD_README;
        case 10000: return REFRESH;
        case 600: return CREATE_ORDER;
        case 601: return QUERY_ORDER;
        case 999: return PUT_CLIENT_IP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<CmdCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CmdCode>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CmdCode>() {
            public CmdCode findValueByNumber(int number) {
              return CmdCode.valueOf(number);
            }
          };

    private final int value;

    private CmdCode(int index, int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.CmdCode)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
