// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProxyServerPutIp.proto

package proto;

public final class ProxyServerPutIpProto {
  private ProxyServerPutIpProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface ProxyServerPutIpOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.ProxyServerPutIp)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string clientIP = 1;</code>
     *
     * <pre>
     *客户端IP
     * </pre>
     */
    boolean hasClientIP();
    /**
     * <code>required string clientIP = 1;</code>
     *
     * <pre>
     *客户端IP
     * </pre>
     */
    java.lang.String getClientIP();
    /**
     * <code>required string clientIP = 1;</code>
     *
     * <pre>
     *客户端IP
     * </pre>
     */
    com.google.protobuf.ByteString
        getClientIPBytes();
  }
  /**
   * Protobuf type {@code proto.ProxyServerPutIp}
   */
  public static final class ProxyServerPutIp extends
      com.google.protobuf.GeneratedMessageLite implements
      // @@protoc_insertion_point(message_implements:proto.ProxyServerPutIp)
      ProxyServerPutIpOrBuilder {
    // Use ProxyServerPutIp.newBuilder() to construct.
    private ProxyServerPutIp(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProxyServerPutIp(boolean noInit) { this.unknownFields = com.google.protobuf.ByteString.EMPTY;}

    private static final ProxyServerPutIp defaultInstance;
    public static ProxyServerPutIp getDefaultInstance() {
      return defaultInstance;
    }

    public ProxyServerPutIp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.ByteString unknownFields;
    private ProxyServerPutIp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.ByteString.Output unknownFieldsOutput =
          com.google.protobuf.ByteString.newOutput();
      com.google.protobuf.CodedOutputStream unknownFieldsCodedOutput =
          com.google.protobuf.CodedOutputStream.newInstance(
              unknownFieldsOutput);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFieldsCodedOutput,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              clientIP_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        try {
          unknownFieldsCodedOutput.flush();
        } catch (java.io.IOException e) {
        // Should not happen
        } finally {
          unknownFields = unknownFieldsOutput.toByteString();
        }
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<ProxyServerPutIp> PARSER =
        new com.google.protobuf.AbstractParser<ProxyServerPutIp>() {
      public ProxyServerPutIp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProxyServerPutIp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProxyServerPutIp> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int CLIENTIP_FIELD_NUMBER = 1;
    private java.lang.Object clientIP_;
    /**
     * <code>required string clientIP = 1;</code>
     *
     * <pre>
     *客户端IP
     * </pre>
     */
    public boolean hasClientIP() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string clientIP = 1;</code>
     *
     * <pre>
     *客户端IP
     * </pre>
     */
    public java.lang.String getClientIP() {
      java.lang.Object ref = clientIP_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientIP_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string clientIP = 1;</code>
     *
     * <pre>
     *客户端IP
     * </pre>
     */
    public com.google.protobuf.ByteString
        getClientIPBytes() {
      java.lang.Object ref = clientIP_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIP_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      clientIP_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasClientIP()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getClientIPBytes());
      }
      output.writeRawBytes(unknownFields);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getClientIPBytes());
      }
      size += unknownFields.size();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static proto.ProxyServerPutIpProto.ProxyServerPutIp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(proto.ProxyServerPutIpProto.ProxyServerPutIp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code proto.ProxyServerPutIp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          proto.ProxyServerPutIpProto.ProxyServerPutIp, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:proto.ProxyServerPutIp)
        proto.ProxyServerPutIpProto.ProxyServerPutIpOrBuilder {
      // Construct using proto.ProxyServerPutIpProto.ProxyServerPutIp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        clientIP_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public proto.ProxyServerPutIpProto.ProxyServerPutIp getDefaultInstanceForType() {
        return proto.ProxyServerPutIpProto.ProxyServerPutIp.getDefaultInstance();
      }

      public proto.ProxyServerPutIpProto.ProxyServerPutIp build() {
        proto.ProxyServerPutIpProto.ProxyServerPutIp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public proto.ProxyServerPutIpProto.ProxyServerPutIp buildPartial() {
        proto.ProxyServerPutIpProto.ProxyServerPutIp result = new proto.ProxyServerPutIpProto.ProxyServerPutIp(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.clientIP_ = clientIP_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(proto.ProxyServerPutIpProto.ProxyServerPutIp other) {
        if (other == proto.ProxyServerPutIpProto.ProxyServerPutIp.getDefaultInstance()) return this;
        if (other.hasClientIP()) {
          bitField0_ |= 0x00000001;
          clientIP_ = other.clientIP_;
          
        }
        setUnknownFields(
            getUnknownFields().concat(other.unknownFields));
        return this;
      }

      public final boolean isInitialized() {
        if (!hasClientIP()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.ProxyServerPutIpProto.ProxyServerPutIp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.ProxyServerPutIpProto.ProxyServerPutIp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object clientIP_ = "";
      /**
       * <code>required string clientIP = 1;</code>
       *
       * <pre>
       *客户端IP
       * </pre>
       */
      public boolean hasClientIP() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string clientIP = 1;</code>
       *
       * <pre>
       *客户端IP
       * </pre>
       */
      public java.lang.String getClientIP() {
        java.lang.Object ref = clientIP_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            clientIP_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string clientIP = 1;</code>
       *
       * <pre>
       *客户端IP
       * </pre>
       */
      public com.google.protobuf.ByteString
          getClientIPBytes() {
        java.lang.Object ref = clientIP_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string clientIP = 1;</code>
       *
       * <pre>
       *客户端IP
       * </pre>
       */
      public Builder setClientIP(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientIP_ = value;
        
        return this;
      }
      /**
       * <code>required string clientIP = 1;</code>
       *
       * <pre>
       *客户端IP
       * </pre>
       */
      public Builder clearClientIP() {
        bitField0_ = (bitField0_ & ~0x00000001);
        clientIP_ = getDefaultInstance().getClientIP();
        
        return this;
      }
      /**
       * <code>required string clientIP = 1;</code>
       *
       * <pre>
       *客户端IP
       * </pre>
       */
      public Builder setClientIPBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        clientIP_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:proto.ProxyServerPutIp)
    }

    static {
      defaultInstance = new ProxyServerPutIp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:proto.ProxyServerPutIp)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
